<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'cinemagia.ro',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-04-09',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Bucharest',
  'culture' => 'ro',
  'max_day' => '7',
  'rating_system' => 'CNA',
  'srating_system' => 'IMDB',
  'url1' => 'https://www.cinemagia.ro/dispatcher.php?controller=ProgramTvGrid&_action=get_tiles_info',
  'requestOption1' => '2',
  'post_data1' => 'ts_start=##urldate1##&ts_end=##stopdate1##&stations%5B%5D=##channel##',
  'accept_header1' => 'text/javascript, text/html, application/xml, text/xml, */*',
  'content_type1' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'host_header1' => 'www.cinemagia.ro',
  'origin_header1' => 'https://www.cinemagia.ro',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'unix',
  'stopdate_format1' => 'unix',
  'show' => '\\{("id".*?)\\}(?:,|\\})',
  'start' => '"ts_start":"(\\d+)',
  'start_format' => 'unix',
  'stop' => '"ts_end":"(\\d+)',
  'stop_format' => 'unix',
  'title' => '<div class="mb5">(.*?)<\\/div>|>|<h2(?: class="inline pr2")?>(.*?)<\\/h2>',
  'title_original' => '<h2 class="inline pr2">(.*?)<\\/h2>||#culture#en',
  'desc' => '"description":"(.*?)","|>|<h3>(.*?)<\\/h3>',
  'showicon' => '<img src="(.*?)"',
  'channel_logo' => '||#add#https://static.cinemagia.ro/img/tv_station/##cclogo##.jpg',
  'actor' => 'title="Actor - (.*?)">',
  'director' => 'title="Regia - (.*?)">',
  'pagekey1' => '<h2 class="inline pr2"><a href="(.*?)"',
  'detail_url1' => '##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html; charset=UTF-8',
  'detail_host_header1' => 'www.cinemagia.ro',
  'detail_desc' => '"og:description" content="(.*?)"\\/>',
  'detail_category' => '"genre":\\["(.*?)"\\]||#split#(",")',
  'detail_showicon' => '"og:image" content="(.*?)"',
  'detail_production_date' => '"og:title" content=".*?\\((\\d{4})\\)"\\/>',
  'detail_actor' => '"actor":\\[(\\{.*?)\\}\\]||#replace#(\\{.*?(?:","name":"|$))##(",".*?\\|)##(".*?$)|||##|##||#split#(\\|)',
  'detail_director' => '"director":\\[(\\{.*?)\\}\\]||#replace#(\\{.*?(?:","name":"|$))##(",".*?\\|)##(".*?$)|||##|##||#split#(\\|)',
  'detail_premiere' => 'Premiera în România <\\/h3>(.*?)<\\/span>',
  'detail_rating' => '"contentRating":"(.*?)"||#upper#',
  'detail_star_rating' => 'IMDB:\\s(\\d(?:\\.\\d+)?)|>|"ratingValue":"(\\d+(?:\\.\\d+)?)||#addend#/10',
  'ccurl1' => 'https://www.cinemagia.ro/program-tv/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'cchost_header1' => 'www.cinemagia.ro',
  'ccchannel_block' => '<li class="station-container">.*?<\\/li>',
  'ccchannel_id' => 'data-station-id="(\\d+)',
  'ccchannel_name' => 'class="station-link">(.*?)<\\/a>',
  'ccchannel_logo' => '\\/program-tv\\/(.*?)\\/" title',
);
?>