<?php return array (
  'filename' => 'tvarenasport.si',
  'creator_name' => 'Kivanc',
  'creation_date' => '2021-11-29',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Ljubljana',
  'culture' => 'sl',
  'max_day' => '7',
  'url1' => 'https://www.tvarenasport.si/ajax/ajax_tv_guide.php',
  'requestOption1' => '2',
  'post_data1' => 'action_type=load_program_scheme_for_day&selected_date=##urldate1##&channel_ids=##channel##&layout_views=horizontal_view',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'content_type1' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'referer_header1' => 'https://www.tvarenasport.si/tv-spored/',
  'host_header1' => 'www.tvarenasport.si',
  'origin_header1' => 'https://www.tvarenasport.si',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'Y-m-d',
  'show' => '"horizontal_view":\\[.*?(?:\\{)(.*?)(?:\\}).*?\\]',
  'start' => '"start":"(.*?)","',
  'start_format' => 'Y-m-d H:i:s',
  'stop' => '"end":"(.*?)","',
  'stop_format' => 'Y-m-d H:i:s',
  'title' => '<div class="second_line">(.*?)<\\/div>',
  'category' => '<span class="sport">(.*?)<\\/span>|#|<span class="event">(.*?)<\\/span>|#|<span class="(live_icon)">||#replace#live_icon||Live||#addend# , ##detail##||#split#(,)',
  'channel_logo' => '||#add#https://www.tvarenasport.si/uploads/web/a##channel##logo.png',
  'pagekey1' => '"id":"(\\d+)',
  'detail_url1' => 'https://www.tvarenasport.si/ajax/ajax_program_scheme_info.php',
  'detail_requestOption1' => '2',
  'detail_post_data1' => 'action_type=load_description_info&ps_record_id=##pagekey1##',
  'detail_accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'detail_content_type1' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'detail_referer_header1' => 'https://www.tvarenasport.si/tv-spored/',
  'detail_host_header1' => 'www.tvarenasport.si',
  'detail_origin_header1' => 'https://www.tvarenasport.si',
  'detail_XMLHttpRequest1' => 'on',
  'detail_desc' => '<div id="modal_content_details">(.*?)<\\/div>',
  'detail_category' => '<div class="modal_sport mt_1">(.*?)<\\/div>',
  'detail_showicon' => '<img src="(.*?)"',
  'ccurl1' => 'https://www.tvarenasport.si/tv-spored/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'ccreferer_header1' => 'https://www.tvarenasport.si/',
  'cchost_header1' => 'www.tvarenasport.si',
  'ccchannel_block' => '<ul id="vertical_navigation_programs".*?(?:<li role=)(.*?)(?:<\\/li>).*?<\\/ul>',
  'ccchannel_id' => 'data-prog_num="(\\d+)',
  'ccchannel_name' => 'alt="(.*?)\\.||#word#',
);
?>