<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tvsporedi.si',
  'creator_name' => 'Kivanc',
  'creation_date' => '2020-03-21',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Ljubljana',
  'culture' => 'sl',
  'max_day' => '3.1',
  'srating_system' => 'IMDb',
  'episodeOption' => '1',
  'url1' => 'http://www.tvsporedi.si/spored.php?urr=##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=UTF-8',
  'host_header1' => 'www.tvsporedi.si',
  'show' => '<div class="ti(.*?)(?:<\\/div>(?:<div>|<div (?:class="clear">|style="clear: both;">)|(?:\\s*)?<\\/div>\\s*<\\/div>))',
  'start' => 'me">(\\d{2}[\\.:]\\d{2})<',
  'start_format' => 'H#i',
  'title' => '<div class="prog">(.*?)<\\/div>||#replace#(,(?:\\s)?\\d{4})||',
  'subtitle' => 'desc">(?:I:.*?\\.\\.\\.)?(.*?)<br>',
  'desc' => ' desc">.*?<p>(.*?)<\\/div>|>| desc">(.*?)<\\/div>||#replace#(IMDb ocena:.*?)$||',
  'season' => '<br>[Ss]ezona\\s(\\d+)',
  'episode' => '[Ee]pizoda\\s(\\d+)<br>',
  'channel_logo' => '||#add###cclogo##',
  'production_date' => '<div class="prog">.*?,(?:\\s)?(\\d{4})',
  'actor' => 'desc">I:(?:\\s)?(.*?)(?:;|\\.\\.\\.)||#split#(,\\s)||#replace#(\\s\\(.*?\\)$)||',
  'role' => 'desc">I:(?:\\s)?(.*?\\(.*?)(?:;|\\.\\.\\.)||#split#(\\),\\s)||#replace#^(.*?\\()##(\\))||##',
  'director' => 'desc">I:(?:\\s)?.*?;\\sR:\\s(.*?)\\.\\.\\.||#split#(,\\s)',
  'country' => 'desc">.*?\\s\\d+<br>(.*?)<br><p>',
  'star_rating' => 'IMDb ocena:\\s(\\d+(?:\\.(?:\\d+)?)?\\/10)',
  'ccurl1' => 'http://www.tvsporedi.si/spored.php?urr=&id=',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'cchost_header1' => 'www.tvsporedi.si',
  'ccchannel_block' => '<li class="squared">.*?<\\/li>',
  'ccchannel_id' => '<a href="\\?urr=(.*?)"||#replace#(\\s)||%20',
  'ccchannel_name' => '\\/><span>(.*?)<\\/span><\\/a><\\/li>',
  'ccchannel_logo' => '<img src="(.*?)"',
);
?>