<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'snrt.ma[fr]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-10-22',
  'rev_no' => 'R0',
  'timezone' => 'Africa/Casablanca',
  'culture' => 'fr',
  'max_day' => '7.1',
  'url1' => 'https://www.snrt.ma/fr/##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'www.snrt.ma',
  'urldate_format1' => '#range#Ymd',
  'grabber_1' => 'on',
  'gpattern_1' => '||#add###urldate1##||#replace#(,)|||',
  'show' => 'grille-line (?:##grabber_1##)(.*?)<\\/div>\\s*<\\/div>',
  'start' => '<\\/a>\\s*(\\d+H\\d+)',
  'start_format' => 'H\\Hi',
  'title' => '"program-title-sm">(.*?)<\\/h2',
  'desc' => '<br>\\s*<br>\\s*(.*?)$',
  'category' => '"genre-first">(.*?)<\\/',
  'showicon' => 'src="(.*?)"',
  'channel_logo' => '||#add#https://www.snrt.ma/sites/default/files/##cclogo##',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'https://www.snrt.ma##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_host_header1' => 'www.snrt.ma',
  'detail_desc' => '<p class="syno.*?>\\s*(.*?)\\s*<\\/p>',
  'ccurl1' => 'https://www.snrt.ma/fr/programmes/alaoula',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'www.snrt.ma',
  'ccchannel_block' => '<h4 class="p-1.*?<\\/h4>',
  'ccchannel_id' => '\\/fr\\/(.*?)"',
  'ccchannel_name' => 'alt="(.*?)"',
  'ccchannel_logo' => '\\/files\\/(.*?)"',
);
?>