<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tv-programme.telecablesat.fr',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-06-05',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Paris',
  'culture' => 'fr',
  'max_day' => '8',
  'rating_system' => 'CSA',
  'episodeOption' => '1',
  'url1' => 'https://tv-programme.telecablesat.fr/chaine/##cclogo##/##channel##.html?date=##urldate1##&period=##subpage1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=utf-8',
  'host_header1' => 'tv-programme.telecablesat.fr',
  'urldate_format1' => 'Y-m-d',
  'subpage_format1' => 'morning|noon|afternoon',
  'show' => '(<div class="news">.*?<\\/div>\\s*<\\/div>\\s*<\\/div>\\s*<\\/div>)',
  'start' => '"schedule-hour">(\\d{2}[\\.:]\\d{2})',
  'start_format' => 'H#i',
  'title' => '<h3>(.*?)<\\/h3>',
  'desc' => '<p>(.*?)<\\/p>',
  'showicon' => 'img-full" src="(.*?)"||#replace#^(\\/\\/)||https://',
  'channel_logo' => '||#add#https://tv.cdnartwhere.eu/images/logos_chaines/##cclogo##.png',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'https://tv-programme.telecablesat.fr##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html; charset=utf-8',
  'detail_host_header1' => 'tv-programme.telecablesat.fr',
  'detail_title_original' => '<span>Titre original(?:\\s*)?:<\\/span>(.*?)<\\/div>||#culture#en',
  'detail_subtitle' => '<h2 class="subtitle">(.*?)<\\/h2>|>|<div class="description"><div>(.*?)<\\/div><\\/div>',
  'detail_desc' => '<h2>Résumé<\\/h2>.*?<p>(.*?)<\\/p>',
  'detail_category' => '<span itemprop="genre">(.*?)<\\/span>',
  'detail_season' => '<span itemprop="episodeNumber">(\\d+)',
  'detail_episode' => '<\\/span>\\((\\d+)',
  'detail_episode_total' => 'itemprop="numberOfEpisodes">(\\d+)',
  'detail_production_date' => '<div class="source">.*?\\s-\\s(\\d{4})(?:\\s*)?<\\/div>',
  'detail_actor' => '<span itemprop="actor">(.*?)<\\/span>',
  'detail_role' => '<span itemprop="actor">.*?<\\/span>\\s\\((.*?)\\)',
  'detail_director' => '<div class="text w60" itemprop="director">(.*?)<\\/div>||#split#(,)',
  'detail_composer' => '<span itemprop="musicBy">(.*?)<\\/span>',
  'detail_writer' => '(?:Scénariste|Scénario).*?<div class="text w60">(.*?)<\\/div>||#split#(,)',
  'detail_country' => '<div class="source">(.*?)(?:\\s-\\s\\d{4}\\s)?<\\/div>||#split#(\\s-\\s)',
  'detail_videoquality' => '<h2>Diffusions TV<\\/h2>.*?<span data-toggle="tooltip" class="(.*?)" title||#upper#',
  'detail_audio' => '<h2>Diffusions TV<\\/h2>.*?<span data-toggle="tooltip" class="(stereo)"||#word#',
  'detail_subtitles' => '<h2>Diffusions TV<\\/h2>.*?<span data-toggle="tooltip" class="(ear)"||#type#d',
  'detail_rating' => '<h2>Diffusions TV<\\/h2>.*?<div class="icons"><span class="age-(\\d+)',
  'detail_star_rating' => '<div class="rating rating-(?!0)(\\d(?:[\\.,]\\d+)?)||#addend#/4',
  'ccurl1' => 'https://tv-programme.telecablesat.fr/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=utf-8',
  'cchost_header1' => 'tv-programme.telecablesat.fr',
  'ccchannel_block' => '<a class="lazy-select-bg".*?<\\/a>',
  'ccchannel_id' => '\\/chaine\\/\\d+\\/(.*?)\\.html',
  'ccchannel_name' => '">(.*?)<\\/a>',
  'ccchannel_logo' => 'logos_chaines\\/(\\d+)\\.',
);
?>