<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'ruv.is',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-08-15',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'is',
  'max_day' => '30',
  'rating_system' => 'FRISK',
  'episodeOption' => '1',
  'url1' => 'https://www.ruv.is/gql/||#edit#("start_time_friendly":\\s*")||"start_time_friendly":"##urldate1##T',
  'requestOption1' => '2',
  'post_data1' => '{"operationName":"getSchedule","variables":{"channel":"##channel##","date":"##urldate1##"},"query":"query getSchedule($channel: Channels!, $date: String!) {\\xn  Schedule(channel: $channel, date: $date) {\\xn    events {\\xn      accessible\\xn      accessible_friendly\\xn      closed_subtitles\\xn      title\\xn      slug\\xn      original_title\\xn      subtitle\\xn      duration_friendly\\xn      start_time_friendly\\xn      end_time_friendly\\xn      file_expires\\xn      image\\xn      is_header\\xn      is_live\\xn      is_rerun\\xn      web_accessible\\xn      description\\xn      image\\xn      scope\\xn      rating\\xn      id\\xn      episodeId\\xn      programId\\xn      __typename\\xn    }\\xn    __typename\\xn  }\\xn}\\xn"}',
  'accept_header1' => '*/*',
  'content_type1' => 'application/json',
  'referer_header1' => 'https://www.ruv.is/sjonvarp/dagskra/##channel##/##urldate1##',
  'host_header1' => 'www.ruv.is',
  'origin_header1' => 'https://www.ruv.is',
  'urldate_format1' => 'Y-m-d',
  'show' => '({\\s*"accessible".*?})',
  'sort' => '"start_time_friendly":"(.*?)"',
  'sortflag' => '1',
  'sortorder' => '1',
  'start' => '"start_time_friendly":"(.*?)"',
  'start_format' => 'Y-m-d\\TH#i',
  'title' => '"title":"(.*?)",',
  'title_original' => '"original_title":"(.*?)",||#culture#en',
  'subtitle' => '"subtitle":"(.*?)",||#replace#(\\(\\d+ af \\d+\\))||',
  'desc' => '"description":"(.*?)",',
  'category' => '"is_(live)":true',
  'showicon' => '"image":"(.*?)",||#replace#(\\$\\$IMAGESIZE\\$\\$)||960',
  'episode' => '"subtitle":"\\((\\d+)\\saf\\s\\d+',
  'episode_total' => '"subtitle":"\\(\\d+\\saf\\s(\\d+)',
  'channel_logo' => '||#add#https://d38kdhuogyllre.cloudfront.net/fit-in/150x/filters:quality(65)/hd_posters/logo_##cclogo##.png',
  'pshown' => '"is_rerun":(true)',
  'subtitles' => '"closed_subtitles":(true)',
  'rating' => '"rating":(\\d+)',
  'ccurl1' => 'https://www.ruv.is/sjonvarp/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'www.ruv.is',
  'ccchannel_block' => '"childs":\\s*\\[.*?\\]',
  'ccchannel_id' => '\\/beint\\/(.*?)"',
  'ccchannel_name' => '"title":"(.*?)"',
  'ccchannel_logo' => '\\/beint\\/(.*?)"||#upper#',
);
?>