<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'filmkatalogus.hu',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-08-23',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Budapest',
  'culture' => 'hu',
  'max_day' => '14',
  'episodeOption' => '1',
  'url1' => 'https://www.filmkatalogus.hu/tvmusor-##channel##-##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'www.filmkatalogus.hu',
  'urldate_format1' => 'Y-m-d',
  'show' => '<TD COLSPAN=3>.*?(?:<TR>)(.*?)(?:<\\/TR>).*?<\\/TABLE>||#exclude#<HR>',
  'start' => '<TD VALIGN=\'TOP\'.*?>(\\d+:\\d+)<',
  'start_format' => 'H#i',
  'title' => 'CLASS=\'tabla_link\' title=\'(.*?)\'|>|<B>(.*?)<\\/B>',
  'title_original' => '<BR>\\s*\\((.*?),\\s*\\d{4}\\)||#culture#en',
  'showicon' => '<A HREF=\'javascript: kep\\("(.*?)"',
  'production_date' => '<BR>\\s*\\((?:.*?,\\s*)?(\\d{4})\\)',
  'actor' => '<B>Szereplők:<\\/B>\\s*(.*?)(?:\\.{1,3})?<BR>',
  'director' => '<B>Rendezte:<\\/B>\\s*(.*?)(?:\\.{1,3})?<BR>',
  'pagekey1' => '<a href=\'(\\S*)\' CLASS=\'tabla_link\'',
  'detail_url1' => 'https://www.filmkatalogus.hu##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_host_header1' => 'www.filmkatalogus.hu',
  'detail_title' => '<H1>(.*?)<\\/H1>',
  'detail_title_original' => '<H2>\\((.*?),\\s*\\d{4}\\)<\\/H2>||#culture#en',
  'detail_desc' => '<DIV ALIGN=JUSTIFY>(.*?)<\\/',
  'detail_category' => '<B>Stílus:<\\/B>\\s*(.*?)<BR>||#split#(,)||#word#',
  'detail_actor' => '<TD>Szereplők:<\\/TD>(.*?)<\\/TABLE>||#replace#.*?title=\'(.*?)\'>.*?(?:<HR>|<\\/TR>\\s*)##(\\|)$||\\1|##||#split#(\\|)',
  'detail_role' => '<TD>Szereplők:<\\/TD>(.*?)<\\/TABLE>||#replace#.*?=RIGHT>(.*?)(?: nyomozó)?<\\/DIV>.*?(?:<HR>|<\\/TR>\\s*)##(\\|)$||\\1|##||#split#(\\|)||#replace#(.*?<.*?>.*)||',
  'detail_director' => '<TD>Rendezte:<\\/TD>(.*?)<\\/TABLE>||#replace#.*?title=\'(.*?)\'>.*?(?:<HR>|<\\/TR>\\s*)##(\\|)$||\\1|##||#split#(\\|)',
  'detail_country' => '<B>Nemzet:<\\/B>\\s*(.*?)<BR>||#split#(,)||#word#',
  'ccurl1' => 'https://www.filmkatalogus.hu/tvmusor',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'www.filmkatalogus.hu',
  'ccchannel_block' => '<OPTGROUP LABEL=.*?(?:<OPTION)(.*?)(?:<\\/OPTION>).*?<\\/OPTGROUP>',
  'ccchannel_id' => 'VALUE=\'(.*?)\'',
  'ccchannel_name' => '.*?>(.*?)$',
);
?>