<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'honeybee.it',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-08-02',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Stockholm',
  'culture' => 'sv',
  'max_day' => '6',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'https://www.honeybee.it/tvguide/##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=utf-8',
  'urldate_format1' => 'Y-m-d',
  'show' => 'self-middle text-sm">##channel##<\\/span>\\s*<\\/div>.*?(?:<div  (?:\\:)?class=")(.*?)(?:<\\/div>\\s*<\\/div>\\s*<\\/div>\\s*<\\/div>).*?<(?:div class="md:w-1|footer class)',
  'start' => 'text-center">\\s*(\\d{2}[\\.:]\\d{2})',
  'start_format' => 'H#i',
  'title' => '<span class="flex-1 z-10">(.*?)<\\/span>',
  'channel_logo' => '||#add#https://old.cdn.actor/channel/svg_logo/##cclogo##',
  'pagekey1' => 'fetchProgramme\\((\\d+)',
  'detail_url1' => 'https://www.honeybee.it/api/programme/##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => '*/*',
  'detail_content_type1' => 'application/json; charset=utf-8',
  'detail_title' => '"title":"(.*?)",',
  'detail_subtitle' => '"sub":"(.*?)",||#replace#([Ss]eason\\s\\d+(?:,)?)##([Ee]pisode\\s\\d+(?:\\:)?)||##',
  'detail_desc' => '"description":"(.*?)",',
  'detail_category' => '"is_(live)":true,|#|"type":"(.*?)"||#word#',
  'detail_showicon' => '"image":"(.*?)"',
  'detail_season' => '"sub":"[Ss]eason (\\d+)',
  'detail_episode' => '"sub":".*?[Ee]pisode (\\d+)',
  'detail_production_date' => '"production_year":(\\d+)',
  'detail_country' => '"production_country":\\["(.*?)"\\]||#split#(",")',
  'detail_new' => '"is_(new)":true,',
  'ccurl1' => 'https://www.honeybee.it/tvguide/##urldate1##',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=utf-8',
  'ccurldate_format1' => 'Y-m-d',
  'ccchannel_block' => '<div class="md:w-1\\/4 p-4">.*?<\\/span>',
  'ccchannel_id' => 'text-sm">(.*?)<\\/span>||#replace#(\\()##(\\))||\\(##\\)',
  'ccchannel_name' => 'text-sm">(.*?)<\\/span>',
  'ccchannel_logo' => 'channel\\/svg_logo\\/(.*?)"',
);
?>