<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tv-tabla.se[tv]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-05-16',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Stockholm',
  'culture' => 'sv',
  'max_day' => '7',
  'episodeOption' => '1',
  'url1' => 'https://tv-tabla.se/tabla/##channel##/##urldate1##/',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=utf-8',
  'urldate_format1' => '#weekdayname#mandag|tisdag|onsdag|torsdag|fredag|lordag|sondag',
  'show' => '(<tr class="u">.*?<\\/tr>)',
  'start' => '<td>(\\d{2}[:\\.]\\d{2})<\\/td>',
  'start_format' => 'H#i',
  'title' => '<h2.*?>(.*?)<\\/h2>',
  'desc' => '<p>(.*?)<\\/p>',
  'pagekey1' => '<a href="(.*?)"',
  'detail_url1' => 'https://tv-tabla.se##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html; charset=utf-8',
  'detail_desc' => '<\\/span><p>(.*?)<\\/p>',
  'detail_category' => '<i class="fa fa-(film)" aria-hidden="true">',
  'detail_showicon' => '<img src="(.*?)"',
  'detail_season' => '<span class="episode"><i class="fa fa-tv" aria-hidden="true"><\\/i>S(?:äsong\\s)?(\\d+)',
  'detail_episode' => '<span class="episode"><i class="fa fa-tv" aria-hidden="true"><\\/i>(?:S(?:äsong\\s)?\\d+(?:\\.)?\\s*)?(?:E|Del\\s*)(\\d+)',
  'detail_episode_total' => '<span class="episode"><i class="fa fa-tv" aria-hidden="true"><\\/i>(?:S(?:äsong\\s)?\\d+(?:\\.)?\\s*)?(?:E|Del\\s*)\\d+\\sav\\s(\\d+)',
  'detail_production_date' => '<i class="fa fa-calendar" aria-hidden="true"><\\/i>(\\d{4})',
  'detail_actor' => '<li class="fat">Medverkande:<\\/li>(.*?)<\\/li><\\/ul>||#split#(<\\/li>)',
  'detail_director' => '<span class="fat">Regi: <\\/span>(.*?)<\\/p>',
  'ccurl1' => 'https://tv-tabla.se/ajax/listtvchannels',
  'ccrequestOption1' => '2',
  'ccaccept_header1' => '*/*',
  'cccontent_type1' => 'text/html; charset=utf-8',
  'ccorigin_header1' => 'https://tv-tabla.se',
  'ccchannel_block' => '<li><a href=".*?<\\/li>',
  'ccchannel_id' => 'href="\\/tabla\\/(.*?)\\/',
  'ccchannel_name' => '<\\/i>(.*?)<\\/a>',
);
?>