<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'zap.co.ao',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-01-30',
  'rev_no' => 'R0',
  'remarks' => 'Rewrite',
  'timezone' => 'UTC',
  'culture' => 'pt',
  'max_day' => '7',
  'episodeOption' => '1',
  'url1' => 'https://zapon.zapsi.net/ao/m/api/epg/events?date=##urldate1##&channel=##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'content_type1' => 'application/json',
  'host_header1' => 'zapon.zapsi.net',
  'origin_header1' => 'https://www.zap.co.ao',
  'urldate_format1' => 'Ymd',
  'show' => '({"eventId".*?})',
  'start' => '"utcBeginDate":(\\d+)',
  'start_format' => 'unix',
  'stop' => '"utcEndDate":(\\d+)',
  'stop_format' => 'unix',
  'title' => '"programName":"(.*?)","||#replace#(\\s*(?:T|Ep)\\.\\d+.*)||',
  'subtitle' => '"subtitle":"(.*?)",',
  'desc' => '"programDescription":"(.*?)","',
  'category' => '"categoryName":"(.*?)",',
  'showicon' => '"pictureUrl":"(.*?)"||#addstart#https://zapon.zapsi.net',
  'season' => '"season":"(\\d+)|>|\\s*T\\.(\\d+)',
  'episode' => '"episode":"(\\d+)|>|\\s*Ep\\.(\\d+)',
  'channel_logo' => '||#add#https://zapon.zapsi.net/public/img/ch/##cclogo##',
  'ccurl1' => 'https://zapon.zapsi.net/ao/m/api/epg/channels',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cccontent_type1' => 'application/json',
  'cchost_header1' => 'zapon.zapsi.net',
  'ccorigin_header1' => 'https://www.zap.co.ao',
  'ccurldate_format1' => 'Y-n-j',
  'ccchannel_block' => '{"_id".*?"position":',
  'ccchannel_id' => '"id":"(\\d+)',
  'ccchannel_name' => '"name":"(.*?)",',
  'ccchannel_logo' => '"image":"(.*?)"',
);
?>