<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'zap.co.ao',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-01-30',
  'rev_no' => 'R0',
  'remarks' => 'Rewrite',
  'timezone' => 'UTC',
  'culture' => 'pt',
  'max_day' => '7',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'http://137.74.115.87/_api/channels/##urldate1##/epg.json',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'urldate_format1' => 'Y-n-j',
  'show' => '"id":##channel##,.*?"epg":\\[.*?(?:{)(.*?)(?:}).*?\\]}',
  'sort' => '"date":"(.*?)T|#|"start_time":"(.*?)"||#replace#(-|h)||',
  'sortflag' => '2',
  'sortorder' => '1',
  'start' => '"date":"(.*?T)|#|"start_time":"(.*?)"||#replace#(h)||:',
  'start_format' => 'Y-m-d\\TH#i',
  'stop' => '"date":"(.*?T)|#|"end_time":"(.*?)"||#replace#(h)||:',
  'stop_format' => 'Y-m-d\\TH#i',
  'title' => '"name":"(.*?)","||#replace#(\\s*(?:T|Ep)\\.\\d+.*)||',
  'subtitle' => '"subtitle":"(.*?)",',
  'desc' => '"sinopse":"(.*?)","',
  'season' => '"season":"(\\d+)|>|\\s*T\\.(\\d+)',
  'episode' => '"episode":"(\\d+)|>|\\s*Ep\\.(\\d+)',
  'channel_logo' => '||#add#http://137.74.115.87/media/cache/movie_thumb/uploads/ao/channels/##cclogo##',
  'ccurl1' => 'http://137.74.115.87/_api/channels/##urldate1##/epg.json',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'ccurldate_format1' => 'Y-n-j',
  'ccchannel_block' => '{"image_uri".*?"number"',
  'ccchannel_id' => '"id":(\\d+)',
  'ccchannel_name' => '"name":"(.*?)",',
  'ccchannel_logo' => '\\/channels\\/(.*?)"',
);
?>