<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'SchedulesDirect[Json][Showicons]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-03-05',
  'rev_no' => 'R0',
  'remarks' => 'Json API with Showicons',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '20.1',
  'rating_system' => 'TVPG',
  'srating_system' => 'Gracenote',
  'episodeOption' => '2',
  'url1' => 'https://json.schedulesdirect.org/20141201/token',
  'requestOption1' => '2',
  'post_data1' => '{"username":"##username##","password":"##password##"}||#hash#sha1#,"password":"(.*?)"\\}$',
  'content_type1' => 'application/json;charset=UTF-8',
  'grabber_1' => 'on',
  'gpattern_1' => '"code":0,.*?"token":"(.*?)"',
  'url2' => 'https://json.schedulesdirect.org/20141201/schedules',
  'requestOption2' => '2',
  'post_data2' => '[{"stationID":"##channel##","date":["##urldate2##"]}]||#replace#((?<!"),)||","',
  'content_type2' => 'application/json;charset=UTF-8',
  'custom_header2' => 'token: ##grabber_1##',
  'urldate_format2' => '#range#Y-m-d',
  'grabber_3' => 'on',
  'gpattern_3' => '(.+)||#replace#(\\R)##.*?\\{"programID":"(.*?)","##(.*?)(,airDateTime.*?)$##((?:[^,]+,){4999}[^,]+),||##"\\1",##[\\1]##\\1]|[',
  'grabber_4' => 'on',
  'gpattern_4' => '(.+)||#replace#(\\R)||',
  'url3' => 'https://json.schedulesdirect.org/20141201/programs',
  'requestOption3' => '2',
  'post_data3' => '##subpage3##',
  'content_type3' => 'application/json;charset=UTF-8',
  'custom_header3' => 'token: ##grabber_1##',
  'subpage_format3' => '##grabber_3##',
  'grabber_5' => 'on',
  'gpattern_5' => '(.+)||#replace#(\\R)##("awards":\\[.*?\\])##(\\{(?:"resourceID":"\\d+",)?"programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\},)\\{(?:"resourceID":"\\d+",)?"programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,|\\])?||####\\1',
  'grabber_6' => 'on',
  'gpattern_6' => '(.+)||#replace#(\\R)##("awards":\\[.*?\\])##\\{(?:"resourceID":"\\d+",)?"programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,)?(\\{(?:"resourceID":"\\d+",)?"programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,|\\])?)||####\\1',
  'url4' => 'https://json.schedulesdirect.org/20141201/metadata/programs/',
  'requestOption4' => '2',
  'post_data4' => '##subpage4##',
  'content_type4' => 'application/json;charset=UTF-8',
  'subpage_format4' => '##grabber_7##',
  'grabber_7' => 'on',
  'gpattern_7' => '(.+)||#url2#||#replace#(\\R)##.*?\\{"programID":"(.*?)","##(.*?)(,airDateTime.*?)$##(\\w{10})(\\w{4})##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##("\\w+",)(.*?)(\\1)##((?:[^,]+,){499}[^,]+),||##"\\1",##[\\1]##\\1##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1\\2##\\1]|[',
  'grabber_8' => 'on',
  'gpattern_8' => '(.+)||#replace#(\\R)##((?:,)?\\{"programID":"\\w+","data":\\{"response":"INVALID_PROGRAMID".*?\\}\\}(?:,)?)##((?:,)?\\{"width":"[\\w",\\.:]+"ratio":"[^6]:[^9]".*?\\}(?:,)?)##(\\{"width":"(?!960).*?\\}(?:,)?)##(\\}\\{)||########},{',
  'show' => '(.+)||#replace#(\\R)##(.+)##((?:\\[\\{)?"stationID".*?\\{)||####grabber_4####||#split#(\\},\\{)||#exclude#SCHEDULE_RANGE_EXCEEDED||#replace#($)##(^"programID":"(\\w+)".*?")(programID)":"\\2","titles":##((?:\\[)?\\{"resourceID":"\\d+","programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,|\\])?)##((?!^)"programID":".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,)?)||##grabber_5####\\1XprogramID":"\\2","titles":####||#replace#($)##(^"programID":"(\\w+)".*?")(programID)":"\\2","titles":##((?:\\[)?\\{"resourceID":"\\d+","programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,|\\])?)##((?!^)"programID":".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,)?)||##grabber_6####\\1XprogramID":"\\2","titles":####||#replace#($)##(^"programID":"(\\w{10}).*?")(programID)":"\\2","data":##((?:\\[|,)?\\{"programID":"\\w+","data".*?".*?\\}\\]\\}(?:,)?)||##grabber_8####\\1XprogramID":"\\2","data":##',
  'start' => '"airDateTime":"(.*?)","',
  'start_format' => 'Y-m-d\\TH:i:s\\Z',
  'duration' => ',"duration":(\\d+)||#format#s',
  'title' => '"title120":"(.*?)"(?:\\}|,")',
  'title_original' => '"titleLanguage":"(.*?)"(?:\\}|,")||#culture#en',
  'subtitle' => '"episodeTitle150":"(.*?)","',
  'desc' => '"description1000":\\[\\{"descriptionLanguage":"\\w+","description":"(.*?)"(?:\\}|,")|>|"description100":\\[\\{"descriptionLanguage":"\\w+","description":"(.*?)"(?:\\}|,")',
  'category' => '"genres":\\["(.*?)"\\]|#|[|","|]"entityType":"(.*?)",|#|[|","|]"showType":"(.*?)"|#|[|","|],"liveTapeDelay":"(Live)"||#split#(",")',
  'showicon' => '"uri":"([\\w\\.]+)","ratio||#addstart#https://json.schedulesdirect.org/20141201/image/',
  'season' => '"season":(\\d+)',
  'episode' => '"episode":(\\d+)',
  'episode_total' => '"totalEpisodes":(\\d+)',
  'channel_logo' => '||#add#https://schedulesdirect-api20141201-logos.s3.amazonaws.com/stationLogos##cclogo##',
  'production_date' => '"movie":\\{"year":"(\\d+)',
  'actor' => '\\{"billingOrder":"\\d+","role":"Actor","\\S+"name":"(.*?)"',
  'role' => '\\{"billingOrder":"\\d+","role":"Actor","\\S+"name":".*?","characterName":"(.*?)"',
  'director' => '\\{"billingOrder":"\\d+","role":"(?:Art )?Director","\\S+"name":"(.*?)"',
  'presenter' => '\\{"billingOrder":"\\d+","role":"(?:Host|Anchor|Presenter)","\\S+"name":"(.*?)"',
  'producer' => '\\{"billingOrder":"\\d+","role":"(?:Executive |Associate )?Producer","\\S+"name":"(.*?)"',
  'composer' => '\\{"billingOrder":"\\d+","role":"(?:Original )?Music","\\S+"name":"(.*?)"',
  'editor' => '\\{"billingOrder":"\\d+","role":"(?:Film )?Editor","\\S+"name":"(.*?)"',
  'commentator' => '\\{"billingOrder":"\\d+","role":"(?:Voice|Commentator)","\\S+"name":"(.*?)"',
  'writer' => '\\{"billingOrder":"\\d+","role":"(?:Writer(?:\\s\\(Story\\))?|Screenwriter)","\\S+"name":"(.*?)"',
  'adapter' => '\\{"billingOrder":"\\d+","role":"Cinematographer","\\S+"name":"(.*?)"',
  'guest' => '\\{"billingOrder":"\\d+","role":"(?:Guest(?: Star)?|Contestant)","\\S+"name":"(.*?)"',
  'videoquality' => '"videoProperties":\\[.*?"(hdtv|sdtv|uhdtv|hdr|3d)".*?\\]||#upper#',
  'premiere' => '"isPremiereOrFinale":"(.*?)"',
  'audio' => '"audioProperties":\\[.*?"(surround|stereo|Dolby|dd(?:\\s5\\.1)?|DD(?:\\s5\\.1)?)".*?\\]||#replace#(DD(?:\\s5\\.1)?|Dolby)||dolby digital',
  'pshown' => ',"originalAirDate":"(.*?)"||#convert#Y-m-d#Ymd',
  'keyword' => '"keyWords":\\{(.*?)\\}||#replace#.*?\\[(.*?)]##(")##(,$)##(\\s)||\\1,######-',
  'subtitles' => '"audioProperties":\\[.*?"(cc|CC)".*?\\]',
  'rating' => '\\{"body":"(?:USA Parental Rating|Motion Picture Association)","code":"(.*?)"|#|[| / |]"(?:subRating":|contentAdvisory":\\[)"(.*?)"(?:\\]|\\})||#replace#(",")|||',
  'star_rating' => '"rating":"(\\d+(?:\\.\\d+)?)|#|[|/|]"maxRating":"(\\d+)',
  'new' => ',"new":(true),',
  'ccurl1' => 'https://json.schedulesdirect.org/20141201/token',
  'ccrequestOption1' => '2',
  'ccpost_data1' => '{"username":"##username##","password":"##password##"}||#hash#sha1#,"password":"(.*?)"\\}$',
  'cccontent_type1' => 'application/json;charset=UTF-8',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '"code":0,.*?"token":"(.*?)"',
  'ccurl2' => 'https://json.schedulesdirect.org/20141201/lineups',
  'ccrequestOption2' => '1',
  'cccontent_type2' => 'application/json;charset=UTF-8',
  'cccustom_header2' => 'token: ##grabber_1##',
  'ccgrabber_3' => 'on',
  'ccgpattern_3' => '"lineups":\\[(.*?)\\]||#replace#((?:,)?\\{"lineup":"[\\w-]+","name":"DELETEDLINEUP","isDeleted":true\\})##\\{"lineup":".*?"uri":"(.*?)"\\}(?:,)?##(\\|$)##(\\\\)||##\\1|####',
  'ccurl3' => 'https://json.schedulesdirect.org##subpage3##',
  'ccrequestOption3' => '1',
  'cccontent_type3' => 'application/json;charset=UTF-8',
  'cccustom_header3' => 'token: ##grabber_1##',
  'ccsubpage_format3' => '##grabber_3##',
  'ccchannel_block' => '\\{"stationID":"\\d+","name.*?(?:\\}|\\])\\}',
  'ccchannel_id' => '\\{"stationID":"(.*?)","',
  'ccchannel_name' => '"affiliate":"(.*?)","|>|"name":"(.*?)","|>|,"callsign":"(.*?)","',
  'ccchannel_logo' => '.*\\{"URL":".*?stationLogos(.*?)",\\S+"category":"light"',
);
?>
