<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'SchedulesDirect[Lineup]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-02-26',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'max_day' => '1',
  'url1' => 'https://json.schedulesdirect.org/20141201/token',
  'requestOption1' => '2',
  'post_data1' => '{"username":"##username##","password":"##password##"}||#hash#sha1#,"password":"(.*?)"\\}$',
  'content_type1' => 'application/json;charset=UTF-8',
  'grabber_1' => 'on',
  'gpattern_1' => '"code":0,.*?"token":"(.*?)"',
  'url2' => 'https://json.schedulesdirect.org##channel##',
  'requestOption2' => '4',
  'content_type2' => 'application/json;charset=UTF-8',
  'custom_header2' => 'token: ##grabber_1##',
  'show' => '(\\{"response":"OK".*?\\})',
  'start' => '\\{"response":"OK".*?"datetime":"(.*?)"',
  'start_format' => 'Y-m-d\\TH:i:s\\Z',
  'title' => '\\{"response":".*?"message":"(.*?)",',
  'desc' => '|#|[|Remaining Changes: |]\\{"response":".*?"changesRemaining":(\\d+),',
  'ccurl1' => 'https://json.schedulesdirect.org/20141201/token',
  'ccrequestOption1' => '2',
  'ccpost_data1' => '{"username":"##username##","password":"##password##"}||#hash#sha1#,"password":"(.*?)"\\}$',
  'cccontent_type1' => 'application/json;charset=UTF-8',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '"code":0,.*?"token":"(.*?)"',
  'ccurl2' => 'https://json.schedulesdirect.org/20141201/headends?##cckey##||#replace#(\\/\\d{8}\\/headends\\?\\#\\#cckey\\#\\#)$##(lineups)||##channel####lineups/preview||#replace#(\\.org)$||.org/20141201/lineups',
  'ccrequestOption2' => '1',
  'cccontent_type2' => 'application/json;charset=UTF-8',
  'cccustom_header2' => 'token: ##grabber_1##',
  'ccchannel_block' => '\\{"headend":".*?\\}\\]\\}|\\{"channel".*?\\}|\\{"lineup".*?\\}',
  'ccchannel_id' => ',"uri":"(.*?)"|"channel":"(.*?)"',
  'ccchannel_name' => '|#|[|[~,"location":"(.*?)",~] |]"name":"(.*?)"',
);
?>