<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'SchedulesDirect[Json]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-02-27',
  'rev_no' => 'R0',
  'remarks' => 'Speed Improvement',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '20.1',
  'rating_system' => 'TVPG',
  'srating_system' => 'Gracenote',
  'episodeOption' => '2',
  'url1' => 'https://json.schedulesdirect.org/20141201/token',
  'requestOption1' => '2',
  'post_data1' => '{"username":"##username##","password":"##password##"}||#hash#sha1#,"password":"(.*?)"\\}$',
  'content_type1' => 'application/json;charset=UTF-8',
  'static_url1' => 'on',
  'grabber_1' => 'on',
  'gpattern_1' => '"code":0,.*?"token":"(.*?)"',
  'url2' => 'https://json.schedulesdirect.org/20141201/schedules',
  'requestOption2' => '2',
  'post_data2' => '[{"stationID":"##channel##","date":["##urldate2##"]}]||#replace#((?<!"),)||","',
  'content_type2' => 'application/json;charset=UTF-8',
  'custom_header2' => 'token: ##grabber_1##',
  'urldate_format2' => '#range#Y-m-d',
  'grabber_3' => 'on',
  'gpattern_3' => '(.+)||#replace#(\\R)##.*?\\{"programID":"(.*?)","##(.*?)(,airDateTime.*?)$##((?:[^,]+,){4999}[^,]+),||##"\\1",##[\\1]##\\1]|[',
  'grabber_4' => 'on',
  'gpattern_4' => '(.+)||#replace#(\\R)||',
  'url3' => 'https://json.schedulesdirect.org/20141201/programs',
  'requestOption3' => '2',
  'post_data3' => '##subpage3##',
  'content_type3' => 'application/json;charset=UTF-8',
  'custom_header3' => 'token: ##grabber_1##',
  'subpage_format3' => '##grabber_3##',
  'grabber_5' => 'on',
  'gpattern_5' => '(.+)||#replace#(\\R)##("awards":\\[.*?\\])##(\\{(?:"resourceID":"\\d+",)?"programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\},)\\{(?:"resourceID":"\\d+",)?"programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,|\\])?||####\\1',
  'grabber_6' => 'on',
  'gpattern_6' => '(.+)||#replace#(\\R)##("awards":\\[.*?\\])##\\{(?:"resourceID":"\\d+",)?"programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,)?(\\{(?:"resourceID":"\\d+",)?"programID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,|\\])?)||####\\1',
  'show' => '(.+)||#replace#(\\R)##(.+)##((?:\\[\\{)?"stationID".*?\\{)||####grabber_4####||#split#(\\},\\{)||#exclude#SCHEDULE_RANGE_EXCEEDED||#replace#($)##((?:\\[{)?"programID":"(\\w+)".*?")(programID)":"\\2","##((?:\\[)?(?:\\{)?"programID":"\\w+","resourceID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,|\\])?)||##grabber_5####\\1XprogramID":"\\2","##||#replace#($)##((?:\\[{)?"programID":"(\\w+)".*?")(programID)":"\\2",##((?:\\[)?(?:{)?"programID":"\\w+","resourceID".*?"md5":"[a-zA-Z0-9\\/\\+\\\\]+".*?\\}(?:,|\\])?)||##grabber_6####\\1XprogramID":"\\2","##',
  'start' => '"airDateTime":"(.*?)","',
  'start_format' => 'Y-m-d\\TH:i:s\\Z',
  'duration' => ',"duration":(\\d+)||#format#s',
  'title' => '"title120":"(.*?)"(?:}|,")',
  'title_original' => '"titleLanguage":"(?![a-z])(.*?)"(?:}|,")||#culture#en',
  'subtitle' => '"episodeTitle150":"(.*?)","',
  'desc' => '"description1000":\\[{"descriptionLanguage":"\\w+(?:-\\w+)?","description":"(.*?)"(?:}|,")|>|"description100":\\[{"descriptionLanguage":"\\w+(?:-\\w+)?","description":"(.*?)"(?:}|,")',
  'category' => '"genres":\\["(.*?)"\\]|#|[|","|]"entityType":"(.*?)",|#|[|","|]"showType":"(.*?)"|#|[|","|],"liveTapeDelay":"(Live)"||#split#(",")',
  'showicon' => '"uri":"(.*?)",||#replace#(^assets)##https://json.schedulesdirect.org/20141201/image/assets',
  'season' => '"season":(\\d+)',
  'episode' => '"episode":(\\d+)',
  'episode_total' => '"totalEpisodes":(\\d+)',
  'channel_logo' => '||#add#https://schedulesdirect-api20141201-logos.s3.amazonaws.com/stationLogos##cclogo##',
  'production_date' => '"year":"(\\d+)',
  'actor' => '{"billingOrder":"\\d+","role":"Actor","name":"(.*?)"',
  'role' => '{"billingOrder":"\\d+","role":"Actor","name":".*?","characterName":"(.*?)"',
  'director' => '{"billingOrder":"\\d+","role":"(?:(?:Art|Casting) )?Director","name":"(.*?)"',
  'presenter' => '{"billingOrder":"\\d+","role":"(?:Host|Anchor|Presenter)","name":"(.*?)"',
  'producer' => '{"billingOrder":"\\d+","role":"(?:Executive |Associate )?Producer","name":"(.*?)"',
  'composer' => '{"billingOrder":"\\d+","role":"(?:Original )?Music","name":"(.*?)"',
  'editor' => '{"billingOrder":"\\d+","role":"(?:Film )?Edit(?:or|ing)","name":"(.*?)"',
  'commentator' => '{"billingOrder":"\\d+","role":"(?:Voice|Commentator)","name":"(.*?)"',
  'writer' => '{"billingOrder":"\\d+","role":"(?:Writer(?:\\s\\(Story\\))?|Screenwriter)","name":"(.*?)"',
  'adapter' => '{"billingOrder":"\\d+","role":"Cinematographer","name":"(.*?)"',
  'guest' => '{"billingOrder":"\\d+","role":"(?:Guest(?: Star)?|Contestant)","name":"(.*?)"',
  'country' => ',"country":\\["(.*?)"\\]||#split#(",")',
  'videoquality' => '"videoProperties":\\[.*?"(hdtv|sdtv|uhdtv|hdr|3d)".*?\\]||#upper#',
  'premiere' => '"isPremiereOrFinale":"(.*?)"',
  'audio' => '"audioProperties":\\[.*?"(surround|stereo|Dolby|dd(?:\\s5\\.1)?|DD(?:\\s5\\.1)?)".*?\\]||#replace#(DD(?:\\s5\\.1)?|Dolby)||dolby digital',
  'pshown' => ',"originalAirDate":"(.*?)"||#convert#Y-m-d#Ymd',
  'keyword' => '"keyWords":{(.*?)}||#replace#.*?\\[(.*?)]##(")##(,$)##(\\s)||\\1,######-',
  'subtitles' => '"audioProperties":\\[.*?"(cc|CC|subtitled)".*?\\]',
  'rating' => '\\{"body":"(?:USA Parental Rating|Motion Picture Association|British Board of Film Classification)","code":"(.*?)"|#|[| / |]"(?:subRating":|contentAdvisory":\\[)"(.*?)"(?:\\]|})||#replace#(",")|||',
  'star_rating' => '"rating":"(\\d+(?:\\.\\d+)?)|#|[|/|]"maxRating":"(\\d+)',
  'new' => ',"new":(true),',
  'ccurl1' => 'https://json.schedulesdirect.org/20141201/token',
  'ccrequestOption1' => '2',
  'ccpost_data1' => '{"username":"##username##","password":"##password##"}||#hash#sha1#,"password":"(.*?)"\\}$',
  'cccontent_type1' => 'application/json;charset=UTF-8',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '"code":0,.*?"token":"(.*?)"',
  'ccurl2' => 'https://json.schedulesdirect.org/20141201/lineups',
  'ccrequestOption2' => '1',
  'cccontent_type2' => 'application/json;charset=UTF-8',
  'cccustom_header2' => 'token: ##grabber_1##',
  'ccgrabber_3' => 'on',
  'ccgpattern_3' => '"lineups":\\[(.*?)\\]||#replace#((?:,)?\\{"lineup":"[\\w-]+","name":"DELETEDLINEUP","isDeleted":true\\})##\\{"lineup":".*?"uri":"(.*?)"\\}(?:,)?##(\\|$)##(\\\\)||##\\1|####',
  'ccurl3' => 'https://json.schedulesdirect.org##subpage3##',
  'ccrequestOption3' => '1',
  'cccontent_type3' => 'application/json;charset=UTF-8',
  'cccustom_header3' => 'token: ##grabber_1##',
  'ccsubpage_format3' => '##grabber_3##',
  'ccchannel_block' => '\\{"stationID":"\\d+","name.*?(?:\\}|\\])\\}||#split#(},{"stationID")',
  'ccchannel_id' => '^(?:{"stationID")?:"(.*?)","',
  'ccchannel_name' => '"name":"(.*?)"|#|[| (~,"callsign":"(.*?)"~)|]^(.)||#replace#(.)$||',
  'ccchannel_logo' => '.*\\{"URL":".*?stationLogos(.*?)",\\S+"category":"light"',
);
?>