<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'promo.mytvsuper.com[zh]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-12-21',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Hong_Kong',
  'culture' => 'zh',
  'max_day' => '7.1',
  'url1' => 'https://promo.mytvsuper.com/tc/epg-channel/##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=UTF-8',
  'host_header1' => 'promo.mytvsuper.com',
  'urldate_format1' => '#range#Y-m-d',
  'grabber_1' => 'on',
  'gpattern_1' => '(.)||#replace#(\\R)##(,)||##urldate1####|',
  'show' => '<div class="epg-list" data-date=(?:##grabber_1##)\\s.*?(?:<div class="row">)(.*?)(?:<div class="separator">).*?<div class="separator"><\\/div>\\s*<\\/div>',
  'start' => '<span class="epg-time">(.*?)<\\/span>',
  'start_format' => 'H#i',
  'title' => '<span class="epg-title">(.*?)<\\/span>',
  'channel_logo' => '||#add#https://img.tvb.com/ti_img/MyTVSuperPromo/##cclogo##',
  'ccurl1' => 'https://promo.mytvsuper.com/tc/epg-channel',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'cchost_header1' => 'promo.mytvsuper.com',
  'ccchannel_block' => '<hr class="epg">.*?<\\/a>',
  'ccchannel_id' => '<a.*?\\/epg-channel\\/(.*?)"',
  'ccchannel_name' => '<span class="font_14 font_b">(.*?)<\\/span>',
  'ccchannel_logo' => '<img class="channel-logo" src=".*?MyTVSuperPromo\\/(.*?)"',
);
?>