<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'rthk.hk',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-03-07',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Hong_Kong',
  'culture' => 'zh',
  'max_day' => '14',
  'keepindexpage' => 'on',
  'url1' => 'https://www.rthk.hk/timetable/main_timetable/##urldate1##||#edit#(\\|\\|)|||',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'host_header1' => 'www.rthk.hk',
  'urldate_format1' => 'Ymd',
  'show' => '"key":"##channel##","data":".*?(?:<div class=)(.*?"showTit.*?)(?:<\\\\\\/div>).*?}||#include#timeRow',
  'start' => '"timeRow">\\s*(.*?)\\s*-',
  'start_format' => 'H#i',
  'stop' => '"timeRow">.*?\\s*-\\s*(\\d+:\\d+)',
  'stop_format' => 'H#i',
  'title' => '"showTit" title="(.*?)"',
  'subtitle' => '"showEpi" title="(.*?)"',
  'category' => 'data-cate="\\|(.*?)\\|"||#split#(\\|)',
  'showicon' => 'data-p="(.*?)"',
  'pagekey1' => '"showEpi" title.*?href=\'(.*?)\'',
  'detail_url1' => '##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_host_header1' => 'www.rthk.hk',
  'detail_desc' => '<div class="gistWrap">.*?<p>(.*?)<\\/div>|>|<meta name="description"\\s*content="(.*?)"\\s*\\/>||#replace#(<p\\s+>)||\\n',
  'ccurl1' => 'https://www.rthk.hk/timetable/main_timetable/##urldate1##',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'cchost_header1' => 'www.rthk.hk',
  'ccXMLHttpRequest1' => 'on',
  'ccurldate_format1' => 'Ymd',
  'ccchannel_block' => '{"name":.*?"data"',
  'ccchannel_id' => '"key":"(.*?)"',
  'ccchannel_name' => '"short_eng_name":"(.*?)"',
);
?>