<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'brasil.teleup.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-04-25',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'pt',
  'max_day' => '7',
  'keepindexpage' => 'on',
  'url1' => 'https://teleupapi.revlet.net/service/api/v1/get/token?tenant_code=teleupbrazil&box_id=6aze37f1-1234-5rf8-10d9-e6e39674e2e3&product=teleupbrazil&device_id=61&display_lang_code=POT&device_sub_type=&timezone=UTC',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'content_type1' => 'text/plain; charset=UTF-8',
  'origin_header1' => 'https://brasil.teleup.com',
  'grabber_1' => 'on',
  'gpattern_1' => '"sessionId":"(.*?)"',
  'grabber_2' => 'on',
  'gpattern_2' => '"tenantCode":"(.*?)"',
  'url2' => 'https://teleupapi.revlet.net/service/api/v1/tv/guide?start_time=##urldate1##&end_time=##stopdate1##&page=0&pagesize=100',
  'requestOption2' => '1',
  'accept_header2' => 'application/json, text/plain, */*',
  'content_type2' => 'text/plain; charset=UTF-8',
  'origin_header2' => 'https://brasil.teleup.com',
  'custom_header2' => 'session-id: ##grabber_1##|#|tenant-code: ##grabber_2##|#|box-id: 6aze37f1-1234-5rf8-10d9-e6e39674e2e3',
  'urldate_format2' => 'java',
  'stopdate_format2' => 'java',
  'show' => '"title":"##channel##","imageUrl":"[^"]+"}},"programs":\\[.*?(?:{"hover")(.*?"imageUrl":".*?)(?:}}).*?}}\\]}',
  'start' => '"startTime","value":"(\\d+)',
  'start_format' => 'java',
  'stop' => '"endTime","value":"(\\d+)',
  'stop_format' => 'java',
  'title' => '"key":"name","value":"(.*?)","',
  'desc' => '"subtitle2":"(.*?)","',
  'showicon' => '"imageUrl":"gracenoteepg,(.*?)"||#addstart#http://dpho.tmsimg.com/||#addend#?w=480',
  'channel_logo' => '||#add#https://d229kpbsb5jevy.cloudfront.net/teleup/320/280/content/common/channel/logos/##cclogo##',
  'ccurl1' => 'https://teleupapi.revlet.net/service/api/v1/get/token?tenant_code=teleupbrazil&box_id=6aze37f1-1234-5rf8-10d9-e6e39674e2e3&product=teleupbrazil&device_id=61&display_lang_code=POT&device_sub_type=&timezone=UTC',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cccontent_type1' => 'text/plain; charset=UTF-8',
  'ccorigin_header1' => 'https://brasil.teleup.com',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '"sessionId":"(.*?)"',
  'ccgrabber_2' => 'on',
  'ccgpattern_2' => '"tenantCode":"(.*?)"',
  'ccurl2' => 'https://teleupapi.revlet.net/service/api/v1/tv/guide?page=0&pagesize=100',
  'ccrequestOption2' => '1',
  'ccaccept_header2' => 'application/json, text/plain, */*',
  'cccontent_type2' => 'text/plain; charset=UTF-8',
  'cccustom_header2' => 'session-id: ##grabber_1##|#|tenant-code: ##grabber_2##|#|box-id: 6aze37f1-1234-5rf8-10d9-e6e39674e2e3',
  'ccchannel_block' => '({"channel":{"hover":{.*?}}),"programs"',
  'ccchannel_id' => '"title":"(.*?)"',
  'ccchannel_name' => '"title":"(.*?)"',
  'ccchannel_logo' => '"imageUrl":".*?\\/logos\\/(.*?)"',
);
?>