<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'redeglobo.globo.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-04-05',
  'rev_no' => 'R0',
  'remarks' => 'Updated',
  'timezone' => 'UTC',
  'culture' => 'pt',
  'max_day' => '3.1',
  'rating_system' => 'DJCTQ',
  'episodeOption' => '1',
  'url1' => 'https://redeglobo.globo.com/##channel##/programacao/',
  'requestOption1' => '1',
  'urldate_format1' => '#range#Y-m-d',
  'grabber_1' => 'on',
  'gpattern_1' => '(.)||#replace#(.+)##(,)##(-)||##urldate1####|##(?:\\1)?',
  'show' => 'data-container-date="(?:##grabber_1##)">.*?(?:<div class="row">)(.*?)(?:<\\/div>\\s*<\\/div>\\s*<\\/div>).*?<\\/section>\\s*<\\/div>|"date":"(?:##grabber_1##)T.*?(?:{"composite":)(.*?versionCertification.*?)(?:}}).*?\\]}',
  'start' => 'data-start-time="(\\d+)|"scheduledDate":"(.*?)"||#convert#Y-m-d\\TH:i:sP#U',
  'start_format' => 'unix',
  'title' => '"program-name">(.*?)<\\/|"name":"(.*?)",',
  'title_original' => '<dt>Título Original<\\/dt>\\s*<dd>(.*?)<\\/dd>|,"independentProduction":(?:true|false),"name":"(.*?)"||#culture#en',
  'subtitle' => '"name":".*?\\s-\\s(.*?)","program',
  'desc' => '<p>(.*?)<\\/p>|"subgenre".*?"synopsis":"(.*?)","',
  'category' => '<dt>Gênero<\\/dt>\\s*<dd>(.*?)(?:<dt>|<\\/dl>)|"genre":{"id":\\d+,"name":"(.*?)"|#|"(live)":true,||#split#(<br>|;)||#replace#(live)||AO VIVO',
  'language' => '{"language":"(.*?)"',
  'showicon' => 'id="schedule-thumb".*?<img src="(.*?)"|{"imageUrl":"(.*?)"',
  'season' => '"season":{"id":\\d+,"number":(?!0)(\\d+)',
  'episode' => '"episodeNumber":(?!0)(\\d+)',
  'production_date' => '"yearOfProduction":(\\d{4})',
  'actor' => '<dt>Elenco<\\/dt>\\s*<dd>(.*?)(?:<dt>|<\\/dl>)|"cast":\\[{"name":"(.*?)"}\\]||#split#(<br>|;|"},{"name":"|\\se\\s)',
  'director' => '<dt>Direção<\\/dt>\\s*<dd>(.*?)(?:<dt>|<\\/dl>)|"directors":\\[{"name":"(.*?)"}\\]||#split#(<br>|;|"},{"name":"|\\se\\s)',
  'country' => '<dt>Nacionalidade<\\/dt>\\s*<dd>(.*?)(?:<dt>|<\\/dl>)|"countries":\\["(.*?)"\\]||#split#(<br>|;|",")',
  'videoquality' => '<i class="schedule-item-content-attrac-tecinfo--(hd)|"resolution":"(.*?)"||#upper#',
  'rating' => '"versionCertification":"(.*?)"|#|[| | |]"versionSubCertification":\\["(.*?)"\\]||#replace#(",")|| / ',
  'ccurl1' => 'https://redeglobo.globo.com/globobrasilia/programacao/',
  'ccrequestOption1' => '1',
  'ccchannel_id' => '<option value="https:.*?\\.com\\/(.*?)\\/programacao|{"categoryId":".*?,"url":"https:.*?\\.com\\/(.*?)\\/programacao',
  'ccchannel_name' => '<option value="https:.*?\\.com\\/.*?\\/programacao\\/">(.*?)<\\/option>|{"categoryId":"\\S+","title":"(.*?)"',
);
?>