<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'redeglobo.globo.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-04-05',
  'rev_no' => 'R0',
  'remarks' => 'Updated',
  'timezone' => 'America/Sao_Paulo',
  'culture' => 'pt',
  'max_day' => '3.1',
  'rating_system' => 'DJCTQ',
  'episodeOption' => '1',
  'url1' => 'https://redeglobo.globo.com/##channel##/programacao/',
  'requestOption1' => '1',
  'urldate_format1' => '#range#Y-m-d',
  'grabber_1' => 'on',
  'gpattern_1' => '(.)||#replace#(.+)##(,)##(-)||##urldate1####|##(?:\\1)?',
  'show' => '"date":"(?:##grabber_1##)T.*?(?:{"composite")(.*?versionCertificationConfirmed.*?)(?:}}).*?}}\\]}',
  'start' => '"startTime":"(.*?)"',
  'start_format' => 'H#i#s',
  'title' => '"name":"(.*?)",',
  'title_original' => ',"independentProduction":(?:true|false),"name":"(.*?)"||#culture#en',
  'subtitle' => '"name":".*?\\s-\\s(.*?)","program',
  'desc' => '"subgenre".*?"synopsis":"(.*?)","',
  'category' => '"(?:sub)?genre":{"id":\\d+,"name":"(.*?)"|#|"(live)":true,||#replace#(live)||AO VIVO',
  'language' => '{"language":"(.*?)"',
  'showicon' => '"imageUrl":"(.*?)"',
  'season' => '"season":{"id":\\d+,"number":(?!0)(\\d+)',
  'episode' => '"episodeNumber":(?!0)(\\d+)',
  'production_date' => '"yearOfProduction":(\\d{4})',
  'actor' => '"cast":\\[{"name":"(.*?)"}\\]||#split#("},{"name":"|\\se\\s|;|\\.)',
  'director' => '"directors":\\[{"name":"(.*?)"}\\]||#split#("},{"name":"|\\se\\s|;)',
  'country' => '"countries":\\["(.*?)"\\]||#split#(",")',
  'videoquality' => '"resolution":"(.*?)"||#upper#',
  'rating' => '"versionCertification":"(.*?)"|#|[| | |]"versionSubCertification":\\["(.*?)"\\]||#replace#(",")|| / ',
  'ccurl1' => 'https://redeglobo.globo.com/globobrasilia/programacao/',
  'ccrequestOption1' => '1',
  'ccchannel_id' => '<option value="https:.*?\\.com\\/(.*?)\\/programacao|{"categoryId":".*?,"url":"https:.*?\\.com\\/(.*?)\\/programacao',
  'ccchannel_name' => '<option value="https:.*?\\.com\\/.*?\\/programacao\\/">(.*?)<\\/option>|{"categoryId":"\\S+","title":"(.*?)"',
);
?>