<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'cgates.lt',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-06-14',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Vilnius',
  'culture' => 'lv',
  'max_day' => '7.1',
  'url1' => 'https://www.cgates.lt/tv-kanalai/##channel##/',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=UTF-8',
  'host_header1' => 'www.cgates.lt',
  'urldate_format1' => '#range#Y-m-d',
  'grabber_1' => 'on',
  'gpattern_1' => '(.)||#replace#(.+)##(,)||##urldate1####|',
  'show' => '<div class="dt-fancy-title">(?:##grabber_1##).*?<tbody>(.*?)<\\/tbody>||#split#(<\\/tr>\\s*<tr >)',
  'start' => '<td class="laikas">(\\d{2}[\\.:]\\d{2})',
  'start_format' => 'H#i',
  'title' => '"vc_toggle_title">(.*?)<|>|<td>(.*?)<\\/td>||#replace#(,\\s.*?)$||',
  'subtitle' => '"vc_toggle_title">.*?,\\s(.*?)(?:,\\s\\d{4}|<br)',
  'desc' => '<p>(.*?)<\\/p>',
  'channel_logo' => '||#add#https://www.cgates.lt/wp-content/uploads/##cclogo##',
  'production_date' => '"vc_toggle_title">.*?,\\s(\\d{4})<',
  'ccurl1' => 'https://www.cgates.lt/televizija/tv-programa-savaitei/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'cchost_header1' => 'www.cgates.lt',
  'ccchannel_block' => '<figure class="wpb_wrapper vc_figure ">.*?<\\/figure>',
  'ccchannel_id' => '\\/tv-kanalai\\/(.*?)"',
  'ccchannel_name' => '<h6 >(.*?)<\\/h6>',
  'ccchannel_logo' => '\\/wp-content\\/uploads\\/(.*?)"',
  'ccidremovedup' => 'on',
);
?>