<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tvprograma.15min.lt',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-10-10',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Vilnius',
  'culture' => 'lt',
  'max_day' => '8.1',
  'episodeOption' => '1',
  'url1' => 'https://tvprograma.15min.lt/tv-programa/televizija/##channel##/##subpage1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'tvprograma.15min.lt',
  'urldate_format1' => '#range#Y_m_d',
  'subpage_format1' => '##urldate1##||#replace#(\\d{4}_\\d{2}_\\d{2})(?:,.*?\\d{4}_\\d{2}_\\d{2})?(?:,.*?\\d{4}_\\d{2}_\\d{2})?(?:,.*?\\d{4}_\\d{2}_\\d{2})?(?:,)?##(\\|)$||\\1|##',
  'show' => '(<div href="#" class="item name(?: active)?">.*?<\\/div>\\s*<\\/div>)',
  'start' => '<span>(\\d+:\\d+)',
  'start_format' => 'H#i',
  'title' => '<\\/span>.*?"(.*?)"',
  'title_original' => '<\\/span>.*?"\\s*\\("(.*?)"\\)||#culture#en',
  'desc' => '<div class="full-description" style="display:none;">(.*?)<\\/div>|>|<div class="description show-full-description">(.*?)<\\/div>|>|<div class="description">(.*?)<\\/div>|>|"\\s*\\(".*?"\\)\\.\\s*(.*?)<\\/div>||#replace#(\\s*\\d{4}\\.\\s*)##(\\d+\\s*s(?:ez)?\\.\\s*)##(Rež\\.:\\s*.*?\\.\\s*)##(\\s*Vaidina:.*?\\.\\s*)||######',
  'showicon' => '<img src="(.*?)"',
  'season' => '(\\d+)\\s*sez\\.\\s',
  'episode' => '(\\d+)\\s*s\\.\\s',
  'channel_logo' => '<div class="logo" data-title=".*?<img\\s*src="(.*?)"',
  'production_date' => '(\\d{4})\\.\\s',
  'actor' => 'Vaidina:\\s*(.*?)\\.\\s*||#split#(,)||#replace#(\\s*ir kiti)||',
  'director' => 'Rež\\.:\\s*(.*?)(?:,\\s*Vaidina:|\\.\\s*)||#split#(,)',
  'premiere' => '(\\sPREMJERA\\s)||#replace#(PREMJERA)||true',
  'ccurl1' => 'https://tvprograma.15min.lt/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'tvprograma.15min.lt',
  'ccchannel_block' => 'search_channels = \\[.*?(?:{)(.*?)(?:}).*?\\]',
  'ccchannel_id' => 'tv-programa\\/televizija\\/(.*?)"',
  'ccchannel_name' => '"label":\\s*"(.*?)"',
);
?>