<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'guida.tv',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-01-24',
  'rev_no' => 'R0',
  'remarks' => 'Ciao Amici Miei!',
  'timezone' => 'UTC',
  'culture' => 'it',
  'max_day' => '8',
  'episodeOption' => '1',
  'url1' => 'https://www.guida.tv/programmi-tv/palinsesto/canale/##channel##.html?dt=##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=UTF-8',
  'urldate_format1' => 'Y-m-d',
  'show' => '(<tr>\\s*<td.*?<\\/tr>)',
  'start' => '&tm=(.*?)"||#replace#(%3A)||:',
  'start_format' => 'Y-m-d\\+H#i#s',
  'title' => '<a href.*?>(.*?)<\\/a>||#replace#(\\s*\\(\\d+.*)||',
  'subtitle' => '<h6>(.*?)<||#replace#(\\s+-(?:\\s+)?$)||',
  'category' => 'alt="(?!New)(.*?)">',
  'production_date' => '\\s*\\((\\d{4})\\)',
  'season' => 'Stagione (\\d+)',
  'episode' => 'Episodio (\\d+)',
  'channel_logo' => '<div class="row">.*?<img src="(.*?)"',
  'new' => 'alt="([Nn]ew)">',
  'pagekey1' => '<a href="(.*?)"',
  'detail_url1' => '##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html; charset=UTF-8',
  'detail_desc' => '<h3 class="thin">Info sul programma<\\/h3>.*?<p>(.*?)<\\/p>',
  'detail_category' => 'attributes-genres">(.*?)<\\/div>|#|<span>(live)<||#split#(<\\/span>|\\/)||#word#',
  'detail_showicon' => '<img class.*?src="(.*?)"',
  'detail_production_date' => '<span>(\\d{4})<',
  'detail_season' => 'Stagione (\\d+)',
  'detail_episode' => 'Episodio (\\d+)',
  'detail_actor' => '"single-cast-head">\\s*<strong>(.*?)<\\/strong>\\s*\\(Attore ',
  'detail_role' => '\\(Attore \\/ Attrice\\)\\s*\\.\\.\\s*(.*?)\\s*<',
  'detail_director' => '<strong>([\\w\\s\\.\\-]+)<\\/strong>\\s*\\(Director',
  'detail_producer' => '<strong>([\\w\\s\\.\\-]+)<\\/strong>\\s*\\((?:Produttore|Produzione)',
  'detail_editor' => '<strong>([\\w\\s\\.\\-]+)<\\/strong>\\s*\\(Film Editor',
  'detail_composer' => '<strong>([\\w\\s\\.\\-]+)<\\/strong>\\s*\\(Musica',
  'detail_videoquality' => '<span>(HD|SD|UHD|4K)<',
  'detail_videoaspect' => '<span>(4x3|16x9)||#replace#(x)||:',
  'detail_audio' => '<span>(Stereo)<',
  'detail_subtitles' => '<span>(subtitles)<',
  'ccurl1' => 'https://www.guida.tv/getproviders',
  'ccrequestOption1' => '2',
  'ccpost_data1' => 'provider=Italy',
  'ccaccept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'cccontent_type1' => 'application/x-www-form-urlencoded',
  'ccorigin_header1' => 'https://www.guida.tv',
  'ccXMLHttpRequest1' => 'on',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '(.+)||#replace#.*?"(-\\d+)":\\s*{\\s*"id":\\s*\\d+,\\s*"title".*?}(?:\\s*})?##(\\|)$||\\1|##',
  'ccgrabber_2' => 'on',
  'ccgpattern_2' => '(.+)||#replace#.*?"-\\d+":\\s*{\\s*"id":\\s*\\d+,\\s*"title":\\s*"(.*?)".*?}(?:\\s*})?##(\\|)$||[\\1]|##',
  'ccurl2' => 'https://www.guida.tv/guide/schedule?provider=##subpage2##&region=Italy&TVperiod=Morning&date=##urldate2##&st=0&u_time=0902&is_mobile=1||#edit#(<td class=\\\\"slt.*?\\/td>)##(<thead.*?\\/thead>)##(<td.*?<br>)##(<br>.*?\\/td>)||######',
  'ccrequestOption2' => '2',
  'ccpost_data2' => 'action=1&menu=0&hour=14&minute=0&userdate=##now#D\\+M\\+d\\+Y#',
  'ccaccept_header2' => 'application/json, text/javascript, */*; q=0.01',
  'cccontent_type2' => 'application/x-www-form-urlencoded',
  'ccorigin_header2' => 'https://www.guida.tv',
  'ccXMLHttpRequest2' => 'on',
  'ccurldate_format2' => 'Y-m-d',
  'ccsubpage_format2' => '##grabber_1##', 
  'ccchannel_block' => '<tbody.*?(?:<tr)(.*?)(?:\\/tr>).*?\\/tbody>||#exclude#X Remove#normalRow last||#ccsubpage#set(##grabber_1##)||#cctag#set(##grabber_2##)', 
  'ccchannel_id' => '#__#(.*?\\|##\\|)|#|\\/canale\\/(.*?)\\.html',
  'ccchannel_name' => '^(.*?)#__#|#|[| |]<a.*?>(.*?)<',
);
?>
