<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'guidatv.quotidiano.net',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-08-05',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '4',
  'url1' => 'https://guidatv.quotidiano.net/##channel##/##urldate1##||#edit#( live">IN ONDA)||">##now#H:i#',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'guidatv.quotidiano.net',
  'urldate_format1' => 'd-m-Y',
  'show' => '(<a class="program".*?<\\/a>)',
  'start' => '"hour">\\s*(\\d+[\\.:]\\d+)',
  'start_format' => 'H#i',
  'title' => '"program-title">(.*?)<\\/',
  'category' => '"program-category">(.*?)<\\/',
  'channel_logo' => '||#add#https://immagini.quotidiano.net/?url=https%3A%2F%2Fs3.eu-west-1.amazonaws.com%2Fstatic.guidatv.quotidiano.net%2Fimg%2Floghi_tv%2F##channel##.png&w=100&h=100&fmt=webp&mode=fill&bg=ffffff',
  'production_date' => '"year">\\s*(\\d{4})',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'https://guidatv.quotidiano.net##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_host_header1' => 'guidatv.quotidiano.net',
  'detail_desc' => '"program-description">\\s*(.*?)\\s*<\\/div>',
  'detail_actor' => '"cast">.*?info-items">\\s*(.*?)\\s*<\\/span>\\s*<\\/div>||#split#(<\\/span>(?:\\s*,)?)',
  'detail_director' => '"director">.*?info-items">\\s*(.*?)\\s*<\\/span>\\s*<\\/div>||#split#(<\\/span>|,)',
  'ccurl1' => 'https://guidatv.quotidiano.net/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'guidatv.quotidiano.net',
  'ccchannel_block' => '<header class="channel-header">.*?<\\/header>',
  'ccchannel_id' => '<a href="\\/(.*?)\\/',
  'ccchannel_name' => '"channel-name">(.*?)<\\/',
);
?>