<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'guidatv.sky.it',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-01-06',
  'rev_no' => 'R0',
  'remarks' => 'Rewrite',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '7.1',
  'rating_system' => 'MBACT',
  'episodeOption' => '1',
  'url1' => 'https://apid.sky.it/gtv/v1/events?to=##stopdate1##T23%3A59%3A00Z&pageSize=999&pageNum=0&from=##urldate1##T00%3A00%3A00Z&env=DTH&channels=##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'urldate_format1' => 'Y-m-d',
  'stopdate_format1' => 'Y-m-d||#date#-1day',
  'show' => '"events".*?(?:"logo":)(.*?)(?:}\\]}(?:,{"channel|\\])).*?"total":',
  'start' => '"starttime":"(.*?)Z"',
  'start_format' => 'Y-m-d\\TH:i:s',
  'stop' => '"endtime":"(.*?)Z"',
  'stop_format' => 'Y-m-d\\TH:i:s',
  'title' => '"epgEventTitle":"(.*?)"||#replace#(S(?:t)?\\d+\\s*(?:Ep\\d+\\s*)?-\\s*)##(Ep\\d+\\s*-\\s*)##(Stag\\.\\s*\\d+(?:\\s*-\\s*)?)##(\\s*-\\s*.*)||######',
  'subtitle' => '"contentTitle":"(.*?)"||#replace#^(.*?\\s*-\\s*)||',
  'desc' => '"eventSynopsis":"(.*?)"||#replace#(S(?:t)?\\d+\\s*(?:Ep\\d+\\s*)?-\\s*)##(Ep\\d+\\s*-\\s*)##^(.*?\\s*-\\s*)##(\\d+\\/\\d+\\/\\d+\\s*-\\s*)||######',
  'category' => '"genre":{"id":\\d*,"name":"(.*?)"|#|"subgenre":{"id":\\d*,"name":"(.*?)"',
  'showicon' => '"(?:background|scene)","img":\\{"url":"(.*?)"||#include#md5ChecksumParam||#addstart#https://guidatv.sky.it/||#addend#&tr=n-scene_ar43_800',
  'season' => '"seasonNumber":(?!0)(\\d+),|>|St(?:ag)?(?:\\.)?(?:\\s*)?(\\d+)',
  'episode' => '"episodeNumber":(?!0)(\\d+),|>|Ep(?:\\.)?(?:\\s*)?(\\d+)',
  'channel_logo' => '"logoLight":"(.*?)"||#addstart#https://guidatv.sky.it||#addend#?tr=n-logo_80',
  'image' => '"(?:cover|scene_key_art)","img":\\{"url":"(.*?)"||#include#md5ChecksumParam||#addstart#https://guidatv.sky.it/||#addend#&tr=n-scene_ar43_800',
  'pagekey1' => '"uuid":"(.*?)"',
  'detail_url1' => 'https://apid.sky.it/gtv/v1/contents/##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'application/json, text/plain, */*',
  'detail_content_type1' => 'application/json;charset=UTF-8',
  'detail_desc' => '"contentSynopsis":"(.*?)",||#replace#(S(?:t)?\\d+\\s*(?:Ep\\d+\\s*)?-\\s*)##(Ep\\d+\\s*-\\s*)##^(.*?\\s*-\\s*)##(\\d+\\/\\d+\\/\\d+\\s*-\\s*)||######',
  'detail_showicon' => '"(?:background|scene)","img":\\{"url":"(.*?)"||#include#md5ChecksumParam||#addstart#https://guidatv.sky.it/||#addend#&tr=n-scene_ar43_800',
  'detail_production_date' => '"productionYear":"(\\d+)',
  'detail_actor' => '{"role":"Attore","person":"(.*?)"}',
  'detail_director' => '{"role":"Regista","person":"(.*?)"}',
  'detail_presenter' => '{"role":"Conduttore","person":"(.*?)"}',
  'detail_producer' => '{"role":"Produttore","person":"(.*?)"}',
  'detail_writer' => '{"role":"Creatore","person":"(.*?)"}',
  'detail_image' => '"(?:cover|scene_key_art)","img":\\{"url":"(.*?)"||#include#md5ChecksumParam||#addstart#https://guidatv.sky.it/||#addend#&tr=n-scene_ar43_800',
  'detail_country' => '"productionCountry":"(.*?)"||#split#(,)',
  'detail_rating' => '"parentalControl":{"type":"SKY","value":"SKY-(.*?)"',
  'ccurl1' => 'https://apid.sky.it/gtv/v1/channels?env=DTH',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cccontent_type1' => 'application/json;charset=UTF-8',
  'ccchannel_id' => '{"id":(\\d*),"logo',
  'ccchannel_name' => '","name":"(.*?)","',
);
?>