<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'guidatv.org',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-12-28',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '7',
  'episodeOption' => '1',
  'url1' => 'https://guidatv.org/canali/##channel##/##stopdate1##__##urldate1##||#replace#(1__.*?)$##(2__.*?)$##(3__.*?)$##(\\d__)||##domani##dopodomani##||#edit#(id="program-)||id="program-##stopdate1##__##urldate1##?share=',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'guidatv.org',
  'urldate_format1' => '#weekdayname#lunedi|martedi|mercoledi|giovedi|venerdi|sabato|domenica',
  'stopdate_format1' => '#daycounter#0',
  'show' => '(<h3 class="hour.*?<\\/div>\\s*<\\/div>\\s*<\\/div>\\s*<\\/div>)',
  'start' => 'timeline (?:text-secondary|live-program)">(\\d+:\\d+)',
  'start_format' => 'H#i',
  'title' => 'title">(.*?)<',
  'desc' => '<p class="program-description.*?>(.*?)<\\/p>',
  'category' => 'text-primary">(.*?)<\\/',
  'showicon' => 'srcSet=".*?(https.*?\\.jpg)||#replace#(%2F)##(%3A)||/##:||#addend#?w=750&q=100',
  'channel_logo' => '||#add#https://img-guidatv.org/loghi/b//##cclogo##',
  'production_date' => '-->\\s*(\\d{4})\\s*<\\!',
  'star_rating' => 'fw-medium">(\\d(?:\\.\\d+))||#addend#/5',
  'pagekey1' => 'id="program-(.*?)"||#replace#^(1__.*?\\?)##^(2__.*?\\?)##^(3__.*?\\?)##^(\\d__)||?##/domani?##/dopodomani?##/',
  'detail_url1' => 'https://guidatv.org/canali/##channel####pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_host_header1' => 'guidatv.org',
  'detail_subtitle' => 'Titolo episodio<\\/p>.*?grey mb-1">(.*?)<\\/p>',
  'detail_desc' => 'Trama episodio<\\/p>.*?prog-desc">(.*?)<\\/p>|>|prog-desc">(.*?)<\\/p>',
  'detail_season' => 'Stagione\\s*(\\d+)',
  'detail_episode' => 'Episodio\\s*(\\d+)',
  'detail_production_date' => 'Anno:\\s*<.*?>(\\d{4})',
  'detail_actor' => '"Immagine Attore (.*?)"',
  'detail_director' => 'Regia:\\s*<.*?>(.*?)\\s*<||#split#(,)',
  'detail_country' => 'Paese di produzione:\\s*<.*?>(.*?)<\\/||#split#(,|\\/)',
  'ccurl1' => 'https://guidatv.org/canali',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'guidatv.org',
  'ccchannel_block' => '(?:{\\\\"logo.*?,)?\\\\"name\\\\":.*?}||#include#"number',
  'ccchannel_id' => '"name":"(.*?)"||#replace#(\\s)||-||#lower#',
  'ccchannel_name' => '"name":"(.*?)"',
  'ccchannel_logo' => '"logo":"(.*?)"',
);
?>