<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'intv.stasera.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-08-19',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '7',
  'url1' => 'https://intv.stasera.com/##channel##/XXXX##stopdate1##--##urldate1##||#replace#(XXXX1.*)##(XXXX2.*)##(XXXX\\d+\\-\\-)||oggi##domani##||#replace#(Monday)##(Tuesday)##(Wednesday)##(Thursday)##(Friday)##(Saturday)##(Sunday)||lunedi##martedi##mercoledi##giovedi##venerdi##sabato##domenica',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'host_header1' => 'intv.stasera.com',
  'cookie_jar1' => 'on',
  'urldate_format1' => 'l',
  'stopdate_format1' => '#daycounter#0',
  'grabber_1' => 'on',
  'gpattern_1' => '<\\/div>\\s*<\\/div>\\s*<div wire:snapshot="(.*?)"||#replace#(\\\\\\\\)##(&quot;)##(xxxx)||\\\\\\\\\\\\\\\\xxxx##\\\\"##',
  'grabber_2' => 'on',
  'gpattern_2' => 'data-csrf="(.*?)"',
  'url2' => 'https://intv.stasera.com/livewire/update',
  'requestOption2' => '2',
  'post_data2' => '{"_token":"##grabber_2##","components":[{"snapshot":"##grabber_1##","updates":{},"calls":[{"path":"","method":"loadMore","params":[]}]}]}',
  'accept_header2' => '*/*',
  'content_type2' => 'application/json',
  'host_header2' => 'intv.stasera.com',
  'origin_header2' => 'https://intv.stasera.com',
  'cookie_jar2' => 'on',
  'show' => '<div class=\\\\"listing-item\\\\">(.*?)<\\\\\\/div>\\\\n\\\\n\\s*<\\\\\\/div>',
  'start' => '<p class="time.*?>\\s*(\\d+[\\.:]\\d+)',
  'start_format' => 'G#i',
  'title' => '<h3 class="uppercase.*?>(.*?)<\\/h3>',
  'desc' => '<span class="">(.*?)<\\/',
  'category' => '<span class="font-bold.*?>(.*?)<\\/',
  'showicon' => '<img src="(.*?)"',
  'premiere' => '>(Prima Tv)<',
  'ccurl1' => 'https://intv.stasera.com/oggi',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'intv.stasera.com',
  'ccchannel_block' => '<li class="relative.*?<\\/li>',
  'ccchannel_id' => 'stasera\\.com\\/(.*?)\\/',
  'ccchannel_name' => '<a class=.*?>\\s*(.*?)\\s*<',
);
?>