<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'libero.it',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-05-27',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '7',
  'url1' => 'https://www.libero.it/magazine/guida-tv/?dt=##stopdate1##__##urldate1##&fo=24&ch=##channel##||#replace#(dt=1__\\w+)##(dt=2__\\w+)##(dt=\\d+__)(\\w+)||dt=oggi##dt=domani##dt=\\2',
  'requestOption1' => '1',
  'urldate_format1' => '#weekdayname#lunedi|martedi|mercoledi|giovedi|venerdi|sabato|domenica',
  'stopdate_format1' => '#daycounter#0',
  'show' => '(<li id=".*?<\\/li>)||#exclude#hour live text-right">',
  'start' => 'hour text-right">\\s*(\\d+[\\.:]\\d+)',
  'start_format' => 'H#i',
  'title' => '"name">\\s*(.*?)\\s*<\\/div>',
  'category' => '"tipology">\\s*(.*?)\\s*<\\/span>',
  'channel_logo' => '<section class="programming">.*?data-src="(.*?)"||#addstart#https://www.libero.it',
  'actor' => '"cast">\\s*Con:\\s*(.*?)<\\/span>||#split#(,) ',
  'length' => 'time">\\s*(\\d+)',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => '##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_host_header1' => 'www.libero.it',
  'detail_title_original' => 'Titolo originale:<\\/strong>\\s*(?!-)(.*?)\\s*<\\/li>||#replace#^(-)$||||#culture#en',
  'detail_desc' => '<p class="h2">(.*?)<\\/p>',
  'detail_category' => 'Genere:<\\/strong>\\s*(?!-)(.*?)\\s*<\\/li>||#split#(,)||#replace#^(-)$||',
  'detail_showicon' => '<link rel="preload" href="(.*?)"',
  'detail_production_date' => 'Anno:<\\/strong>\\s*(\\d+)',
  'detail_actor' => 'Cast:<\\/strong>\\s*(?!-)(.*?)\\s*<\\/li>||#split#(,)||#replace#^(-)$||',
  'detail_director' => 'Regia:<\\/strong>\\s*(?!-)(.*?)\\s*<\\/li>||#split#(,)||#replace#^(-)$||',
  'detail_presenter' => 'Conduce:<\\/strong>\\s*(?!-)(.*?)\\s*<\\/li>||#split#(,)||#replace#^(-)$||',
  'detail_country' => 'Nazione:<\\/strong>\\s*(?!-)(.*?)\\s*<\\/li>||#split#(,)||#replace#^(-)$||',
  'ccurl1' => 'https://www.libero.it/magazine/guida-tv/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'www.libero.it',
  'ccchannel_block' => '<input class="form-check-input input-ch".*?<\\/li>',
  'ccchannel_id' => 'id="(.*?)"',
  'ccchannel_name' => '<label.*?>\\s*(.*?)\\s*<\\/label>',
);
?>