<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'mediasetplay.mediaset.it',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-05-04',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'it',
  'max_day' => '8',
  'episodeOption' => '1',
  'url1' => 'https://api-ott-prod-fe.mediaset.net/PROD/play/feed/allListingFeedEpg/v2.0?byListingTime=##urldate1##~##stopdate1##&byCallSign=##channel##',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'content_type1' => 'application/json',
  'origin_header1' => 'https://www.mediasetplay.mediaset.it',
  'urldate_format1' => 'javag',
  'stopdate_format1' => 'javag',
  'show' => '({"airingType".*?epgChannelPool":""})',
  'start' => '"startTime":(\\d+)',
  'start_format' => 'java',
  'stop' => '"endTime":(\\d+)',
  'stop_format' => 'java',
  'title' => '"mediasetlisting\\$epgTitle":"(.*?)","||#replace#(\\*s-\\s*PrimaTv)||',
  'subtitle' => '"mediasetlisting\\$shortDescription":"(?!string)(?:S\\d+\\s)?(?:Ep\\d+\\s)?(.*?)","|>|"mediasetprogram\\$titleUI":"(?!string)(.*?)","||#replace#((?:\\s*)?Ep(?:\\.)?\\d+(?:\\s*)?)||',
  'desc' => '"longDescription":"(.*?)","|>|"description":"(.*?)","',
  'category' => '"mediasetprogram\\$genres":\\["(?!string)(.*?)"\\]||#split#(",")',
  'showicon' => '"image_header_poster-\\d+x\\d+":{"url":"(.*?)"',
  'season' => '"mediasetlisting\\$shortDescription":"(?!string)S(\\d+)',
  'episode' => '"mediasetprogram\\$titleUI":"Ep\\.\\s(\\d+)|>|"mediasetlisting\\$shortDescription":"(?!string)(?:S\\d+\\s)?Ep(\\d+)',
  'channel_logo' => '"channel_logo-100x100":{"url":"(.*?)"',
  'country' => '"mediasetprogram\\$countryProduction":\\["(?!string)(.*?)"\\]||#split#(",")',
  'videoaspect' => '"mediasetprogram\\$sourceAspectRatio":"(.*?)","||#replace#(_)||x',
  'videoquality' => '"mediasetprogram\\$sourceVideoFormat":"(SD|HD)",',
  'premiere' => '"mediasetlisting\\$epgTitle":".*?\\s-\\s(PrimaTv)","||#replace#(PrimaTv)||true',
  'pshown' => '"airingType":"(repeat)"',
  'new' => '"airingType":"(new)"',
  'ccurl1' => 'https://feed.entertainment.tv.theplatform.eu/f/PR1GhC/mediaset-prod-all-stations-v2?sort=shortTitle|asc&form=cjson&httpError=true',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cccontent_type1' => 'text/plain;charset=UTF-8',
  'cchost_header1' => 'feed.entertainment.tv.theplatform.eu',
  'ccorigin_header1' => 'https://www.mediasetplay.mediaset.it',
  'ccchannel_block' => '({"id":".*?"mediasetstation\\$pageUrl.*?})',
  'ccchannel_id' => '"callSign":"(.*?)",',
  'ccchannel_name' => '"title":"(.*?)","callSign"',
);
?>