<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'movietele.it',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-07-04',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '7.1',
  'srating_system' => 'mtRating',
  'episodeOption' => '1',
  'url1' => 'https://www.movietele.it/guidatv/##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'show' => '<tr>(.*?)<\\/tr>',
  'start' => '<td class="voci">(\\d{2}:\\d{2})',
  'start_format' => 'H#i',
  'title' => '<a title=".*?>(.*?)<\\/a>|>|<td>(.*?)\\s<',
  'desc' => 'class="hddn">(.*?)<\\/||#replace#^((?:\\s*)?- )||',
  'channel_logo' => '<source srcset=\'(.*?)\\?||#replace#^(\\/\\/)||https://',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'https://www.movietele.it##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html; charset=utf-8',
  'detail_subtitle' => 'Titolo Italiano:\\s*<\\/span>(.*?)<br|>|Titolo Originale:\\s*<\\/span>(.*?)<br',
  'detail_desc' => '(?:(?:TRAMA|Trama)<\\/h2>|<div class="schede.*?>)<p>(.*?)<\\/p>',
  'detail_category' => 'Genere:\\s*<\\/span>(.*?)<br||#split#(,)',
  'detail_showicon' => '<meta property="og:image" content="(.*?)"||#replace#^(\\/\\/)||https://',
  'detail_season' => 'Stagion(?:i|e):\\s*<\\/span>(\\d+)',
  'detail_episode' => 'Episodi(?:o)?:\\s*<\\/span>(\\d+)',
  'detail_production_date' => 'Nazione:\\s*<\\/span>.*? - (\\d{4})|>|Anno:\\s*<\\/span>(\\d{4})',
  'detail_actor' => 'Cast Artistico e Ruoli:\\s*<\\/span>(.*?)<\\/div><\\/div>||#replace#.*?<\\/figure><br>(.*?)<\\/a>.*?<\\/small>||\\1,||#split#(,)',
  'detail_role' => 'Cast Artistico e Ruoli:\\s*<\\/span>(.*?)<\\/div><\\/div>||#replace#.*?<small>(.*?)<\\/small>||\\1,||#split#(,)||#replace#(-)||',
  'detail_director' => 'Regia:\\s*<\\/span>(.*?)<br||#split#(,)',
  'detail_producer' => 'Produttori:\\s*<\\/span>(.*?)<br><hr>||#replace#.*?<a href.*?>(.*?)<\\/a>.*?<\\/small>||\\1,||#split#(,)',
  'detail_composer' => 'Musiche:\\s*<\\/span>(.*?)<br||#split#(,)',
  'detail_editor' => 'Montaggio:\\s*<\\/span>(.*?)<br||#split#(,)',
  'detail_writer' => 'Sceneggiatura:\\s*<\\/span>(.*?)<br||#split#(,)',
  'detail_country' => 'Nazione:\\s*<\\/span>(.*?)(?: - |<br>)',
  'detail_colour' => 'Formato:\\s*<\\/span> (Colore)||#replace#(Colore)||yes',
  'detail_length' => 'Durata:\\s*<\\/span> (\\d+)',
  'detail_star_rating' => 'itemprop="ratingValue">Media:\\s*<span >(\\d+(?:\\.\\d+)?)||#addend#/10',
  'ccurl1' => 'https://www.movietele.it/guidatv',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'ccchannel_block' => '<div class="boxchannel.*?<\\/div>',
  'ccchannel_id' => '<a href="\\/guidatv\\/(.*?)"',
  'ccchannel_name' => 'alt="(.*?)"',
);
?>