<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'raiplay.it',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-05-04',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '8',
  'episodeOption' => '1',
  'url1' => 'https://www.raiplay.it/palinsesto/app/##channel##/##urldate1##.json',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'content_type1' => 'application/json;charset=UTF-8',
  'urldate_format1' => 'd-m-Y',
  'show' => '({ "id" : "Content.*?})',
  'start' => '"hour" : "(.*?)", "',
  'start_format' => 'H#i',
  'duration' => '"duration_in_minutes" : "(\\d+)||#format#m',
  'title' => '"name" : "(.*?)", "||#replace#(\\s-\\s.*?)$##((?:-)?\\s*(?:S|E(?:P|p)?)\\d+.*?)$||##',
  'subtitle' => '"episode_title" : "(.*?)", "',
  'desc' => '"description" : "(.*?)", "',
  'showicon' => '"image" : "(.*?)"||#addstart#https://www.raiplay.it/resizegd/720x-',
  'season' => '"season" : "(?!0)(\\d+)',
  'episode' => '"episode" : "(?!0)(\\d+)',
  'pagekey1' => '"path_id" : "(\\/video.*?)"',
  'detail_url1' => 'https://www.raiplay.it##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => '*/*',
  'detail_content_type1' => 'application/json;charset=UTF-8',
  'detail_category' => '"(?:sub_)?genres": \\["(.*?)"]|#|"is_(live)": true,||#split#(",")',
  'detail_season' => '"season": "(\\d+)',
  'detail_episode' => '"episode": "(\\d+)',
  'detail_production_date' => '"key":"year","value":"(\\d{4})',
  'detail_actor' => '"actors": "(.*?)",||#split#(,|;|\\/| e )',
  'detail_director' => '"direction": "(.*?)",||#split#(,|;|\\/| e )',
  'detail_presenter' => '"presenter": "(.*?)",||#split#(,|;|\\/| e )',
  'detail_writer' => '"author": "(.*?)",||#split#(,|;|\\/| e )',
  'detail_country' => '"key":"country","value":"(.*?)"||#split#(,|;|\\/)',
  'ccurl1' => 'https://www.raiplay.it/guidatv',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html;charset=UTF-8',
  'ccchannel_block' => '({"label":".*?})',
  'ccchannel_id' => '"absolute_path":"(.*?)",',
  'ccchannel_name' => '"name":"(.*?)",',
);
?>