<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'rakuten.tv[it]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-04-09',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '7.1',
  'srating_system' => 'IMDB',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'https://gizmo.rakuten.tv/v3/live_channels?classification_id=36&device_identifier=web&device_stream_audio_quality=2.0&device_stream_hdr_type=NONE&device_stream_video_quality=FHD&epg_ends_at=##stopdate1##T00%3A00%3A00.000Z&epg_starts_at=##urldate1##T00%3A00%3A00.000Z&locale=it&market_code=it&per_page=500',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'host_header1' => 'gizmo.rakuten.tv',
  'origin_header1' => 'https://rakuten.tv',
  'urldate_format1' => 'Y-m-d',
  'stopdate_format1' => 'Y-m-d',
  'show' => '{"type":"live_channels","id":"##channel##",".*?,"live_programs":\\[.*?(?:"type":"live_programs")(.*?)(?:}(?:}|,{)).*?\\]}',
  'start' => '"starts_at":"(.*?)\\.',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"ends_at":"(.*?)\\.',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"title":"(.*?)"||#replace#(\\s\\(\\d{4}\\))$##^(S\\d+\\sE\\d+\\s-\\s)||##',
  'subtitle' => '"subtitle":"(.*?)",||#replace#^(.*?\\s\\|\\s)||',
  'desc' => '"description":"(.*?)","',
  'category' => '"is_(live)":true',
  'season' => '"subtitle":"S(\\d+)|>|"title":"S(\\d+)\\s',
  'episode' => '"subtitle":"(?:S\\d+\\s:\\s)?E(\\d+)|>|"title":"(?:S\\d+\\s)?E(\\d+)\\s',
  'channel_logo' => ',"id":"##channel##.*?{"artwork":"(.*?)"||#replace#(\\.png|\\.jpeg)$||-width308-quality100\\1',
  'production_date' => '"title":".*?\\s\\((\\d{4})\\)"',
  'pagekey1' => '"movie_id":"(.*?)"',
  'detail_url1' => 'https://gizmo.rakuten.tv/v3/movies/##pagekey1##?classification_id=36&device_identifier=web&locale=it&market_code=it',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'application/json, text/plain, */*',
  'detail_host_header1' => 'gizmo.rakuten.tv',
  'detail_origin_header1' => 'https://rakuten.tv',
  'detail_title' => '"title":"(.*?)",',
  'detail_title_original' => '"original_title":"(.*?)",',
  'detail_desc' => '"plot":"(.*?)","|>|"short_plot":"(.*?)","',
  'detail_category' => '{"type":"genres",.*?"name":"(.*?)"',
  'detail_showicon' => '"snapshot":"(.*?)"|#|"images":{"artwork":"(.*?)"||#replace#(\\.png|\\.jpeg)$||-width480-quality100\\1',
  'detail_production_date' => '"year":(\\d{4})',
  'detail_actor' => '"actors":\\[(.*?)]||#split#(},{)||#replace#.*?"name":"(.*?)".*$||\\1',
  'detail_director' => '"directors":\\[(.*?)]||#split#(},{)||#replace#.*?"name":"(.*?)".*$||\\1',
  'detail_country' => '{"type":"countries",.*?"name":"(.*?)"',
  'detail_rating' => '"age":(?!0)(\\d+)',
  'detail_star_rating' => 'imdb\\.com\\/title.*?"score":(?!0)(\\d+(?:\\.\\d+)?)||#addend#/10',
  'ccurl1' => 'https://gizmo.rakuten.tv/v3/live_channels?classification_id=36&device_identifier=web&device_stream_audio_quality=2.0&device_stream_hdr_type=NONE&device_stream_video_quality=FHD&epg_ends_at=##urldate1##T01%3A00%3A00.000Z&epg_starts_at=##urldate1##T00%3A00%3A00.000Z&locale=it&market_code=it&per_page=500',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cchost_header1' => 'gizmo.rakuten.tv',
  'ccorigin_header1' => 'https://rakuten.tv',
  'ccurldate_format1' => 'Y-m-d',
  'ccchannel_block' => '{"type":"live_channels".*?"classification"',
  'ccchannel_id' => ',"id":"(.*?)",',
  'ccchannel_name' => ',"title":"(.*?)",',
);
?>