<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'sorrisi.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-07-29',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'it',
  'max_day' => '2.1',
  'episodeOption' => '1',
  'url1' => 'https://www.sorrisi.com/guidatv/canali-tv/##channel##/',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'www.sorrisi.com',
  'show' => '(<article class="gtv-program.*?<\\/article>)',
  'start' => 'data-start-ts="(\\d+)',
  'start_format' => 'unix',
  'stop' => 'data-end-ts="(\\d+)',
  'stop_format' => 'unix',
  'title' => 'program-title">(.*?)<\\/h3',
  'desc' => '<p class="gtv-program-abstract">(.*?)<\\/p>',
  'category' => 'alt="(.*?)"||#addend#,##detail##||#split#(,|\\/)',
  'showicon' => '<img src="(.*?)"||#replace#^(\\/\\/)##(_small)||https://##_large',
  'season' => 'stagione-(\\d+)|>|Stagione\\s*(\\d+)',
  'episode' => 'episodio-(\\d+)|>|Episodio\\s*(\\d+)',
  'channel_logo' => '||#add#https://www.sorrisi.com/guidatv/bundles/tvscnewsite/css/images/loghi/##channel##.png',
  'pagekey1' => '<a href="(.*?)"||#replace#^(\\/\\/)||https://',
  'detail_url1' => '##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_host_header1' => 'programma.sorrisi.com',
  'detail_title_original' => 'Titolo originale:<\\/strong>\\s*(.*?)\\s*<\\/li>||#culture#en',
  'detail_subtitle' => '<h2 class="gtv-title">(.*?)<\\/h2>',
  'detail_desc' => '<p class="gtv-text.*?>(.*?)<\\/p>',
  'detail_category' => 'Genere:<\\/strong>\\s*(.*?)\\s*<\\/li>',
  'detail_production_date' => 'Uscita:<\\/strong>\\s*(\\d{4})',
  'detail_actor' => 'Cast:<\\/strong>\\s*(.*?)\\s*<\\/li>||#split#(,)',
  'detail_director' => 'Regista:<\\/strong>\\s*(.*?)\\s*<\\/li>||#split#(,)',
  'detail_country' => 'Nazionalità:<\\/strong>\\s*(.*?)\\s*<\\/li>||#split#(,|\\/|\\s*-\\s*)',
  'detail_length' => 'Durata:<\\/strong>\\s*(\\d+)',
  'ccurl1' => 'https://www.sorrisi.com/guidatv/canali-tv/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'www.sorrisi.com',
  'ccchannel_block' => '<h3 class="gtv-mod1-logo">.*?<\\/h3>',
  'ccchannel_id' => '\\/canali-tv\\/(.*?)\\/',
  'ccchannel_name' => 'title="(.*?)"',
);
?>