<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tivu.tv',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-04-03',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Rome',
  'culture' => 'it',
  'max_day' => '7',
  'url1' => 'https://www.tivu.tv/epg_ajax_sat.aspx?d=##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'content_type1' => 'text/html; charset=utf-8',
  'host_header1' => 'www.tivu.tv',
  'urldate_format1' => '#daylist#0|1|2|3|4|5|6',
  'show' => '<div class="q(?:\\sw)?" id=\'##channel##\'>.*?(?:<div)(.*?)(?:<\\/div>).*?<\\/div><\\/div>||#include#-<br>',
  'start' => '-<br>\\s*(\\d+[:\\.]\\d+)\\s*<\\/',
  'start_format' => 'H#i',
  'title' => 'data-channel.*?>(.*?)<br>',
  'category' => 'data-genre="(.*?)"',
  'channel_logo' => '||#add#https://www.tivu.tv/_common/images/loghi_epg/logo_##cclogo##',
  'pagekey1' => ' id=\'(\\d+)',
  'detail_url1' => 'https://www.tivu.tv/scheda-programma.aspx?i=##channel##&p=##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html; charset=utf-8',
  'detail_host_header1' => 'www.tivu.tv',
  'detail_desc' => '<p>(.*?)<\\/p>',
  'ccurl1' => 'https://www.tivu.tv/epg_ajax_sat.aspx?d=0',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => '*/*',
  'cccontent_type1' => 'text/html; charset=utf-8',
  'cchost_header1' => 'www.tivu.tv',
  'ccXMLHttpRequest1' => 'on',
  'ccchannel_id' => '<div class="q(?:\\sw)?"\\sid=\'(\\d+)',
  'ccchannel_name' => '<a href="schedasat-(.*?)\\.html||#replace#(-)|| ||#word#',
  'ccchannel_logo' => '<img src="_common\\/images\\/loghi_epg\\/logo_(.*?)"',
);
?>