<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'trt.net.tr',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-02-07',
  'rev_no' => 'R0',
  'remarks' => 'New Site Structure',
  'timezone' => '+03:00',
  'culture' => 'tr',
  'max_day' => '3.1',
  'keepindexpage' => 'on',
  'url1' => 'https://www.trt.net.tr/yayin-akisi',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=utf-8',
  'host_header1' => 'www.trt.net.tr',
  'show' => '<h2 class="card-texts">##channel## Yayın Akışı.*?(?:<div class="current">|"livestream-details")(.*?)(?:<\\/div>\\s*<\\/div>).*?(?:<div class="cont">|<div class="large-screenss">)||#exclude#..........',
  'start' => '"livestream-time">\\s*(\\d{2}[\\.:]\\d{2})',
  'start_format' => 'H#i',
  'title' => '"livestream-title">(.*?)<',
  'showicon' => '<img src="(http.*?)"',
  'channel_logo' => '<h2 class="card-texts">##channel## Yayın Akışı.*?<img alt.*?src="(.*?)"',
  'ccurl1' => 'https://www.trt.net.tr/yayin-akisi',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=utf-8',
  'cchost_header1' => 'www.trt.net.tr',
  'ccchannel_block' => 'TELEVİZYON<\\/a><\\/li>.*?(?:<li class="dropdown-item")(.*?)(?:<\\/li>).*?RADYO<\\/a>',
  'ccchannel_id' => '>(.*?)<\\/||#upper#',
  'ccchannel_name' => '>(.*?)<\\/',
  'ccidremovedup' => 'on',
);
?>