<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'devportal.siba.com.co',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-06-30',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'es',
  'max_day' => '30.1',
  'url1' => 'http://devportal.siba.com.co/index.php?action=grilla',
  'requestOption1' => '2',
  'post_data1' => 'ciudad=13&servicio=##ccsubpage##&ini=##urldate1##&end=##stopdate1##&cat=&chn=##channel##&str=&',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'content_type1' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'host_header1' => 'devportal.siba.com.co',
  'origin_header1' => 'http://devportal.siba.com.co',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'unix',
  'stopdate_format1' => 'unix',
  'show' => '"prog":\\[(.*?)\\]||#split#(},{)',
  'start' => '"ini":(\\d+)',
  'start_format' => 'unix',
  'stop' => '"fin":(\\d+)',
  'stop_format' => 'unix',
  'title' => '"nom":"(.*?)",',
  'channel_logo' => '{"id":"##channel##",.*?"logo":"(.*?)"||#addstart#http://cdn-std-1.sibasa.netdna-cdn.com/co/',
  'ccurl1' => 'http://devportal.siba.com.co/index.php?action=servicios',
  'ccrequestOption1' => '2',
  'ccpost_data1' => 'ciudad=13',
  'ccaccept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'cccontent_type1' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'cchost_header1' => 'devportal.siba.com.co',
  'ccorigin_header1' => 'http://devportal.siba.com.co',
  'ccXMLHttpRequest1' => 'on',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '(.+)||#replace#.*?"id":"(?!24|21|25)(\\d+)".*?}(?:\\].*?})?##(.*)\\|.*||\\1|##\\1',
  'ccgrabber_2' => 'on',
  'ccgpattern_2' => '(.+)||#replace#.*?"id":"(?!24|21|25)\\d+".*?"nom":"(.*?)".*?}(?:\\].*?})?##(.*)\\|.*||[\\1]|##\\1',
  'ccurl2' => 'http://devportal.siba.com.co/index.php?action=grilla||#edit#(,"prog":\\[.*?\\])||',
  'ccrequestOption2' => '2',
  'ccpost_data2' => 'ciudad=13&servicio=##subpage2##&ini=##urldate2##&end=##urldate2##&cat=&chn=&str=&',
  'ccaccept_header2' => 'application/json, text/javascript, */*; q=0.01',
  'cccontent_type2' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'cchost_header2' => 'devportal.siba.com.co',
  'ccorigin_header2' => 'http://devportal.siba.com.co',
  'ccXMLHttpRequest2' => 'on',
  'ccurldate_format2' => 'unix',
  'ccsubpage_format2' => '##grabber_1##',
  'ccchannel_block' => '{"list":\\[.*?(?:{)(.*?)(?:}).*?\\]||#ccsubpage#set(##grabber_1##)||#cctag#set(##grabber_2##)',
  'ccchannel_id' => '#__#(.*?\\|##\\|)|#|"id":"(\\d+)',
  'ccchannel_name' => '^(.*?)#__#|#|[| |]"nom":"(.*?)"',
);
?>