<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'winsportsonline.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-04-03',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'es',
  'max_day' => '5.1',
  'keepindexpage' => 'on',
  'url1' => 'https://next.platform.mediastre.am/graphql',
  'requestOption1' => '2',
  'post_data1' => '{"operationName":"getLivesEpg","variables":{"page":1,"hours":120},"query":"query getLivesEpg($page: Int = 1, $hours: Int) {\\xn  getLives {\\xn    _id\\xn    logo\\xn    name\\xn    schedules(hours: $hours, page: {limit: 0, page: $page}) {\\xn      _id\\xn      name\\xn      date_start\\xn      date_end\\xn      description\\xn      current\\xn      match {\\xn        matchDay\\xn        __typename\\xn      }\\xn      show {\\xn        _id\\xn        title\\xn        __typename\\xn      }\\xn      live {\\xn        _id\\xn        dvr\\xn        type\\xn        purchased\\xn        __typename\\xn      }\\xn      __typename\\xn    }\\xn    __typename\\xn  }\\xn}\\xn"}',
  'accept_header1' => '*/*',
  'content_type1' => 'application/json',
  'host_header1' => 'next.platform.mediastre.am',
  'origin_header1' => 'https://www.winsportsonline.com',
  'custom_header1' => 'X-Client-Id: 5cc0fca5aa211a225409a2d629bd180b46952eae3349e59c3f|#|X-Ott-Language: es',
  'show' => '"schedules":\\s*\\[.*?(?:{\\s*"_id")(.*?)(?:"Schedule"\\s*}).*?\\]||#include#"##channel##"',
  'start' => '"date_start":\\s*"(.*?)\\.',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"date_end":\\s*"(.*?)\\.',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"name":\\s*"(.*?)"',
  'description' => '"description":\\s*"(.*?)"',
  'channel_logo' => '{\\s*"_id":\\s*"##channel##",\\s*"logo":\\s*"(.*?)"',
  'ccurl1' => 'https://next.platform.mediastre.am/graphql',
  'ccrequestOption1' => '2',
  'ccpost_data1' => '{"operationName":"getChannels","variables":{"filter":{"field":"type","value":"VIDEO"}},"query":"query getChannels($filter: Filter!) {\\xn  getLives(filter: $filter) {\\xn    _id\\xn    name\\xn    slug\\xn    logo\\xn    customJson\\xn    __typename\\xn  }\\xn}\\xn"}',
  'ccaccept_header1' => '*/*',
  'cccontent_type1' => 'application/json',
  'cchost_header1' => 'next.platform.mediastre.am',
  'ccorigin_header1' => 'https://www.winsportsonline.com',
  'cccustom_header1' => 'X-Client-Id: 5cc0fca5aa211a225409a2d629bd180b46952eae3349e59c3f|#|X-Ott-Language: es',
  'ccchannel_block' => '"_id".*?"customJson"',
  'ccchannel_id' => '"_id":\\s*"(.*?)"',
  'ccchannel_name' => '"name":\\s*"(.*?)"',
);
?>