<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tvwish.com[sl]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-06-21',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'si',
  'max_day' => '7.1',
  'episodeOption' => '1',
  'url1' => 'https://tvwish.com/SL/Channels/UpcomingJson/##channel##',
  'requestOption1' => '2',
  'post_data1' => 'PNo=##subpage1##',
  'accept_header1' => '*/*',
  'content_type1' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'host_header1' => 'tvwish.com',
  'origin_header1' => 'https://tvwish.com',
  'XMLHttpRequest1' => 'on',
  'subpage_format1' => '#counter#1#14',
  'show' => '({"pi.*?})',
  'start' => '"sdtu":"(.*?)"',
  'start_format' => 'Y-m-d\\TH#i#s',
  'title' => '"spn":"(.*?)",',
  'desc' => '"ed":"(.*?)",',
  'showicon' => '"pu":"(.*?)"||#addstart#https://tvwish.com/img/program/',
  'season' => '-S(\\d+)',
  'episode' => '"en":(?!0)(\\d+)',
  'channel_logo' => '||#add#https://tvwish.com/Img/Channel/##channel##.webp',
  'pagekey1' => '"pi":(\\d+)',
  'detail_url1' => 'https://tvwish.com/Program/##pagekey1##/CreditsJson',
  'detail_requestOption1' => '1',
  'detail_actor' => '"name":"(.*?)"',
  'detail_role' => '"character":"(.*?)"',
  'detail_director' => '"dn":"(.*?)"||#split#(,)',
  'ccurl1' => 'https://tvwish.com/SL/Channels/NonTopByCats/0',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'cchost_header1' => 'tvwish.com',
  'ccXMLHttpRequest1' => 'on',
  'ccchannel_block' => '"value":\\[.*?(?:{)(.*?)(?:}).*?\\]',
  'ccchannel_id' => '"i":(\\d+)',
  'ccchannel_name' => '"n":"(.*?)"',
);
?>