<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'bfbs.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-06-06',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '7',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'https://tvplayer.bfbs.com/tvguide-ajax?date=##urldate1##T00%3A00%3A00.000%2B00%3A00',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'host_header1' => 'tvplayer.bfbs.com',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'Y-m-d',
  'show' => '{"id":"##channel##",.*?"tiles":\\[.*?(?:{"id":)(.*?)(?:"userCanWatch".*?}).*?\\]}',
  'start' => '"start":"(.*?)\\+',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"end":"(.*?)\\+',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"title":"(.*?)",',
  'subtitle' => '"episode_title":"(.*?)",',
  'desc' => '"synopsis":"(.*?)",',
  'category' => '"category":"(.*?)"|#|"sub_category":"(.*?)"|#|"genre":"(.*?)"',
  'showicon' => '"category".*?"image":"(.*?)"',
  'season' => '"season":"(?!0)(\\d+)',
  'episode' => '"episode":"(?!0)(\\d+)',
  'channel_logo' => '{"id":"##channel##",.*?"logo":"(.*?)"||#replace#(width=\\d+)||width=150',
  'ccurl1' => 'https://tvplayer.bfbs.com/tvguide-ajax?date=##urldate1##T00%3A00%3A00.000%2B00%3A00',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'cchost_header1' => 'tvplayer.bfbs.com',
  'ccXMLHttpRequest1' => 'on',
  'ccurldate_format1' => 'Y-m-d',
  'ccchannel_block' => '{"id":"\\d+","title":.*?"logo"',
  'ccchannel_id' => '{"id":"(\\d+)',
  'ccchannel_name' => '"title":"(.*?)",',
);
?>