<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'bfbs.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-06-06',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '7',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'https://www.bfbs.com/tv/schedule.json?schedule&ts=##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'host_header1' => 'www.bfbs.com',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'unix',
  'show' => '({"content":".*?})||#include#"group":"##channel##"',
  'start' => '"start":(\\d+)',
  'start_format' => 'java',
  'stop' => '"end":(\\d+)',
  'stop_format' => 'java',
  'title' => 'show-name">(.*?)<\\/',
  'desc' => '.*show-description">(.*?)<\\/',
  'ccurl1' => 'https://www.bfbs.com/tv/schedule.json?schedule&ts=##urldate1##',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => '*/*',
  'cchost_header1' => 'www.bfbs.com',
  'ccXMLHttpRequest1' => 'on',
  'ccurldate_format1' => 'unix',
  'ccchannel_block' => '{"id":"\\d+","content":.*?}',
  'ccchannel_id' => '{"id":"(\\d+)',
  'ccchannel_name' => '"content":"(.*?)",',
);
?>