<?php return array (
  'filename' => 'filmon.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2021-10-06',
  'rev_no' => 'R1',
  'remarks' => 'Api Version',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '7',
  'episodeOption' => '1',
  'pastdayremover' => 'on',
  'url1' => 'https://www.filmon.com/api-v2/tvguide/?startTime=##urldate1##&duration=86400&channels=##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'content_type1' => 'application/json',
  'host_header1' => 'www.filmon.com',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'unix',
  'show' => '"##channel##":\\[.*?(?:\\{)(.*?)(?:\\}).*?\\]\\}',
  'start' => '"startdatetime":(\\d+)',
  'start_format' => 'unix',
  'stop' => '"enddatetime":(\\d+)',
  'stop_format' => 'unix',
  'title' => '"programme_name":"(.*?)","',
  'desc' => '"programme_description":"(.*?)","',
  'season' => '"seriesNumber":((?!0)\\d+)',
  'episode' => '"episodeNumber":((?!0)\\d+)',
  'channel_logo' => '||#add#https://static.filmon.com/assets/channels/##channel##/big_logo.png',
  'ccurl1' => 'https://www.filmon.com/groups/?with-special=true',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'cccontent_type1' => 'application/json',
  'cchost_header1' => 'www.filmon.com',
  'ccXMLHttpRequest1' => 'on',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '(.+)||#replace#.*?"alias":\\s*"(.*?)".*?"channels_count":\\s*\\d+.*?}(?:\\s*\\])?##(\\|)$||\\1|##',
  'ccurl2' => 'https://www.filmon.com/group/##subpage2##',
  'ccrequestOption2' => '1',
  'ccaccept_header2' => 'application/json, text/javascript, */*; q=0.01',
  'cccontent_type2' => 'application/json',
  'cchost_header2' => 'www.filmon.com',
  'ccXMLHttpRequest2' => 'on',
  'ccsubpage_format2' => '##grabber_1##',
  'ccchannel_block' => '{"id":.*?"description":',
  'ccchannel_id' => '"id":(\\d+)',
  'ccchannel_name' => '"title":"(.*?)","',
);
?>