<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'itv.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-01-25',
  'rev_no' => 'R0',
  'timezone' => 'Europe/London',
  'culture' => 'en',
  'max_day' => '6',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'https://www.itv.com/watch/tv-guide/##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=UTF-8',
  'host_header1' => 'www.itv.com',
  'urldate_format1' => 'Y-m-d',
  'show' => 'data-guide-channel="##channel##">.*?(?:<li)(.*?)(?:<\\/li>).*?<\\/ul>\\s*<\\/li>||#replace#>(\\d{1,2})([ap]m) -## - (\\d{1,2})([ap]m)||>\\1.00\\2 -## - \\1.00\\2',
  'start' => '<p class.*?>(.*?) - ',
  'start_format' => 'g.ia',
  'stop' => '<p class.*?>.*? - (.*?)<\\/p>',
  'stop_format' => 'g.ia',
  'title' => '<h4.*?>(.*?)<\\/h4>',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'https://www.itv.com##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html; charset=utf-8',
  'detail_host_header1' => 'www.itv.com',
  'detail_subtitle' => '<script id="__NEXT_DATA__".*?,"episodeTitle":"(.*?)",',
  'detail_desc' => '<script id="__NEXT_DATA__".*?,"synopsis":"(.*?)",',
  'detail_category' => '<script id="__NEXT_DATA__".*?"formattedCapitalised":\\["(.*?)"\\]||#split#(\\&)',
  'detail_showicon' => '<script id="__NEXT_DATA__".*?,"768":{"1x":"(.*?)"',
  'detail_season' => '<script id="__NEXT_DATA__".*?,"seriesNumber":(\\d+)',
  'detail_episode' => '<script id="__NEXT_DATA__".*?,"episodeNumber":(\\d+)',
  'detail_episode_total' => '<script id="__NEXT_DATA__".*?"brandAvailableEpisodeCount":(\\d+)',
  'detail_subtitles' => '<script id="__NEXT_DATA__".*?,"accessibilityTags":\\[.*?"(s)".*?\\]',
  'detail_rating' => '<script id="__NEXT_DATA__".*?,"guidance":"(.*?)"',
  'ccurl1' => 'https://www.itv.com/watch/tv-guide/##urldate1##',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'cchost_header1' => 'www.itv.com',
  'ccurldate_format1' => 'Y-m-d',
  'ccchannel_block' => 'data-guide-type="channel".*?<\\/h3>',
  'ccchannel_id' => 'data-guide-channel="(.*?)">',
  'ccchannel_name' => '<h3.*?>(.*?)<\\/h3>',
);
?>