<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'itv.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-01-25',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '6',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'https://www.itv.com/watch/tv-guide/##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=UTF-8',
  'host_header1' => 'www.itv.com',
  'urldate_format1' => 'Y-m-d',
  'show' => '"##channel##":\s*\[.*?(?:{)(.*?)(?:}).*?\]',
  'start' => '"start":\\s*"(.*?)Z',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"end":\\s*"(.*?)Z',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"title":\\s*"(.*?)"',
  'subtitle' => '"episodeTitle":\\s*"(.*?)"',
  'category' => '"genre":\\s"(.*?)"||#split#(,|\\&)',
  'desc' => '"description":\\s"(.*?)"',
  'showicon' => '"ccid":\\s*"(.*?)"||#addstart#https://ovp.itv.com/images/episode/||#addend#/itv_hub/08_Episodic/16x9?distributionPartner=itv_hub&fallback=standard&w=382&q=80&blur=0&bg=false',
  'season' => '"seriesNumber":\\s*(\\d+)',
  'episode' => '"episodeNumber":\\s*(\\d+)',
  'rating' => '"guidance":\\s*"(.*?)"',
  'ccurl1' => 'https://www.itv.com/watch/tv-guide/##urldate1##?position=start',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'cchost_header1' => 'www.itv.com',
  'ccurldate_format1' => 'Y-m-d',
  'ccchannel_block' => '(?:\\],|{)\\s*"ITV.*?":\\s*\\[\\s*{',
  'ccchannel_id' => '"(.*?)"',
  'ccchannel_name' => '"(.*?)"',
);
?>