<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'skysports.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-07-06',
  'rev_no' => 'R0',
  'timezone' => 'Europe/London',
  'culture' => 'en',
  'max_day' => '7',
  'keepindexpage' => 'on',
  'url1' => 'https://www.skysports.com/watch/tv-guide/##urldate1##||#edit#(\\R)##(<div class="row-table">\\s*)(<div class="col.*?<\\/div>)||##\\1',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html',
  'urldate_format1' => 'd-m-Y',
  'show' => '<div class="row-table">.*?(?:<div class="col)(.*?)(?:<\\/div>).*?<\\/div><!-- row table -->||#repeat###channel##',
  'start' => '\\/tv-guide\\/(.*?)"|#|[| |]<p class="-time">\\s*(\\d+[\\.:]\\d+[ap]m)',
  'start_format' => 'd-m-Y H#ia',
  'title' => '<h4 class="-title.*?>(.*?)<\\/h4>',
  'channel_logo' => '||#add#https://e3.365dm.com/tvlogos/channels/##cclogo##-Mobile-Logo.svg?',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'https://www.skysports.com##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html',
  'detail_content_type1' => 'application/x-www-form-urlencoded',
  'detail_XMLHttpRequest1' => 'on',
  'detail_desc' => '<p>(.*?)<\\/p>',
  'detail_showicon' => '<img src="(\\S*)"\\s',
  'ccurl1' => 'https://www.skysports.com/watch/tv-guide/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html',
  'ccchannel_block' => '<span class="ss-tvlogo.*?<\\/span>',
  'ccchannel_id' => '#counter#0',
  'ccchannel_name' => 'alt="(.*?)"',
  'ccchannel_logo' => '\\/tvlogos\\/channels\\/(\\d+)',
);
?>