<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'uktvplay.co.uk',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-06-03',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '8.1',
  'episodeOption' => '1',
  'url1' => 'https://vschedules.uktv.co.uk/api/epg?channel=##channel##&start=##urldate1##&days=8',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'host_header1' => 'vschedules.uktv.co.uk',
  'origin_header1' => 'https://uktvplay.co.uk',
  'urldate_format1' => 'Y-m-d',
  'show' => '({"brand_id":.*?}\\]\\})',
  'start' => '"start_time":"(.*?)\\+',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"end_time":"(.*?)\\+',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"brand_title":"(.*?)",',
  'subtitle' => '"episode_title":"(.*?)",',
  'desc' => '"synopsis":"(.*?)",',
  'category' => '"bds_genre":"(.*?)"||#split#(:\\s)',
  'showicon' => '"episode_image":"(.*?)"|#|"brand_image":"(.*?)"',
  'season' => '"series_number":"(?!0)(\\d+)',
  'episode' => '"episode_number":(?!0)(\\d+)',
  'episode_total' => '"series_episodes":(?!0)(\\d+)',
  'channel_logo' => '||#add#https://s3-eu-west-1.amazonaws.com/uktv-static/fgprod/play/img/##cclogo##',
  'videoaspect' => '"aspect_ratio":"(.*?)"||#replace#(x)||:',
  'videoquality' => '"format":"(.*?)"',
  'subtitles' => '"subtitle":(true),',
  'new' => '"synopsis":"(New)\\.',
  'ccurl1' => 'https://uktvplay.co.uk/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'uktvplay.co.uk',
  'ccchannel_block' => '{id:[\\d\\w],name:".*?}',
  'ccchannel_id' => 'name:"(.*?)"||#lower#',
  'ccchannel_name' => 'name:"(.*?)"',
  'ccchannel_logo' => 'sqLogo:".*?img\\/(.*?)"',
);
?>