<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'artonline.tv',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-07-27',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Riyadh',
  'culture' => 'ar',
  'max_day' => '6',
  'episodeOption' => '2',
  'url1' => 'https://www.artonline.tv/Home/##channel##',
  'requestOption1' => '2',
  'post_data1' => 'objId=##urldate1##&objtext=+##stopdate1##',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'content_type1' => 'application/x-www-form-urlencoded',
  'host_header1' => 'www.artonline.tv',
  'origin_header1' => 'https://www.artonline.tv',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => '#daycounter#0',
  'stopdate_format1' => 'm\\%\\2\\Fd\\%\\2\\FY||#date#-1day',
  'show' => '({"id".*?})',
  'start' => '"start_Time":"(\\d+:\\d+)',
  'start_format' => 'H#i',
  'title' => '"title":"(.*?)",',
  'desc' => '"description":"(.*?)",|>|"short_description":"(.*?)",',
  'language' => '"lang":"(.*?)"',
  'showicon' => '"thumbnail":"(.*?)"||#addstart#https://beta-artonline.com/?path=/',
  'season' => '"season_Number":(?!0)(\\d+)',
  'episode' => '"epoisode_Number":(?!0)(\\d+)',
  'channel_logo' => '||#add#https://www.artonline.tv/images/ART_Logo/##cclogo##',
  'ccurl1' => 'https://www.artonline.tv/guide/1',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'www.artonline.tv',
  'ccchannel_id' => ' url: "\\/Home\\/(.*?)"',
  'ccchannel_name' => '(?:"|\');\\s*document.getElementById\\("(\\w+)content"\\)',
  'ccchannel_logo' => '<img src="\\.\\.\\/images\\/ART_Logo\\/(.*?)"',
);
?>