<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'live.relevant.co.il',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-11-12',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'he',
  'max_day' => '7.1',
  'rating_system' => 'MPAA',
  'episodeOption' => '1',
  'url1' => 'https://prihadar-prod.cloud.seachange.com/catalogue-search/prihadar/search/public/usercontext/epg/grid?stationIds=##channel##&startTime=##urldate1##T00:00Z&endTime=##stopdate1##T00:00Z',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'host_header1' => 'prihadar-prod.cloud.seachange.com',
  'origin_header1' => 'https://live.relevant.co.il',
  'urldate_format1' => 'Y-m-d',
  'stopdate_format1' => 'Y-m-d',
  'show' => '({"externalIds":.*?,"live":.*?"childRelations":)',
  'start' => '"startTime":\\s*"(.*?)Z"',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"endTime":\\s*"(.*?)Z"',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"title":\\s*"(.*?)",',
  'desc' => '"longDescription":\\s*"(.*?)",|>|"description":\\s*"(.*?)",',
  'category' => '"(live)":\\s*true,',
  'language' => '"language":\\s*"(.*?)",',
  'showicon' => '"cdnUrl":\\s*"(.*?)"',
  'channel_logo' => '||#add#https://prihadar-prod-cdn.cloud.seachange.com/asset/images/RelevantChannelLogo-OCQOp.png',
  'actor' => '"actors":\\s*\\["(.*?)"\\]||#split#(",")',
  'director' => '"directors":\\s*\\["(.*?)"\\]||#split#(",")',
  'producer' => '"producers":\\s*\\["(.*?)"\\]||#split#(",")',
  'pshown' => '"repeat":\\s*(true),',
  'rating' => '"rating":\\s*"(.*?)"',
  'ccurl1' => 'https://prihadar-prod.cloud.seachange.com/catalogue-search/prihadar/search/public/usercontext/epg/stations',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => '*/*',
  'cchost_header1' => 'prihadar-prod.cloud.seachange.com',
  'ccorigin_header1' => 'https://live.relevant.co.il',
  'ccchannel_id' => '"uid":\\s*"(.*?)",\\s*"taxonomyTerms"',
  'ccchannel_name' => '"title":\\s*"(.*?)",\\s*"relations"',
);
?>