<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'entertainment.ie',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-04-13',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Dublin',
  'culture' => 'en',
  'max_day' => '10',
  'episodeOption' => '1',
  'url1' => 'https://entertainment.ie/tv/##channel##/?date=##urldate1##&time=all-day',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=UTF-8',
  'urldate_format1' => 'd-m-Y',
  'show' => '(<li class="lightbox.*?<\\/li>)',
  'start' => '<span class="time">(.*?)<\\/span>',
  'start_format' => 'H#i',
  'duration' => 'data-duration="(\\d+)||#format#m',
  'title' => '<h3><a class="lightbox" href="#popup">(.*?)<span',
  'subtitle' => 'data-title="(.*?)"',
  'desc' => 'data-description="(.*?)"\\s*data',
  'category' => 'data-genres="(.*?)"|#|data-genre="(.*?)"||#split#(,)',
  'showicon' => '"\\s*data-srcset="\\S+,(.*?)\\s2x"',
  'season' => 'data-ep="S(\\d+)',
  'episode' => 'data-ep=".*?Ep(\\d+)',
  'channel_logo' => '||#add#https://s3.eu-west-1.amazonaws.com/entertainmentie/storage/television/tv-logos/##cclogo##',
  'production_date' => 'data-year="(\\d+)',
  'pshown' => '<abbr title="(Repeat) showing">',
  'subtitles' => '<abbr title="(Subtitles) available">',
  'ccurl1' => 'https://entertainment.ie/tv/all-channels/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'ccchannel_block' => 'channels =\'\\[.*?(?:\\{\\&quot;id\\&quot;:)(.*?)(?:platforms).*?\\]\'',
  'ccchannel_id' => '"slug":"(.*?)",',
  'ccchannel_name' => '"name":"(.*?)",',
  'ccchannel_logo' => '\\/tv-logos\\/(.*?)"',
);
?>