<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tdm.com.mo[en]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-04-17',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Macau',
  'culture' => 'en',
  'max_day' => '6',
  'url1' => 'https://www.tdm.com.mo/api/v1.0/program-list/##urldate1##?date=##urldate1##&type=##ccsubpage##&channelId=##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'host_header1' => 'www.tdm.com.mo',
  'custom_header1' => 'Api-Language: en',
  'urldate_format1' => 'Y-m-d',
  'show' => '({"id".*?})',
  'start' => '"date":"(.*?)"',
  'start_format' => 'Y-m-d H#i#s',
  'title' => '"title":"(.*?)",',
  'category' => '"is(News)":true',
  'language' => '"programLang":"([a-z]+)',
  'showicon' => '"channelBackground":"(.*?)"||#addend#,##detail##||#split#(,)',
  'channel_logo' => '||#add#https://cdn.tdm.com.mo/uploads/attachment/##cclogo##',
  'pagekey1' => '"slug":"(.*?)"',
  'detail_url1' => 'https://www.tdm.com.mo/api/v1.0/program/##pagekey1##/details',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'application/json, text/plain, */*',
  'detail_host_header1' => 'www.tdm.com.mo',
  'detail_custom_header1' => 'Api-Language: en',
  'detail_subtitle' => '"headTitle":"(.*?)",',
  'detail_desc' => '"content":"(.*?)",|#|[|\\n|]"playDesc":"(.*?)",',
  'detail_showicon' => '"(?:cover|background)":"(.*?)"',
  'detail_presenter' => '"programHosts":\\["(.*?)"\\]||#split#(",")',
  'detail_guest' => '"programGuest":\\["(.*?)"\\]||#split#(",")',
  'ccurl1' => 'https://www.tdm.com.mo/api/v1.0/program-list/Channel?type=##subpage1##||#edit#({"id":)||\\1##subpage1##|\\#\\#|',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cchost_header1' => 'www.tdm.com.mo',
  'cccustom_header1' => 'Api-Language: en',
  'ccsubpage_format1' => 'tv|radio',
  'ccchannel_block' => '{"id".*?"intro"',
  'ccchannel_id' => '"id":(.*?),',
  'ccchannel_name' => '"title":"(.*?)"',
  'ccchannel_logo' => '\\/attachment\\/(.*?)"',
);
?>