<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'vidio.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-03-23',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Jakarta',
  'culture' => 'id',
  'max_day' => '4',
  'url1' => 'https://www.vidio.com/auth',
  'requestOption1' => '2',
  'post_data1' => ' ||#replace#(\\s)||',
  'accept_header1' => '*/*',
  'host_header1' => 'www.vidio.com',
  'origin_header1' => 'https://www.vidio.com',
  'grabber_1' => 'on',
  'gpattern_1' => '"api_key":"(.*?)"',
  'url2' => 'https://api.vidio.com/livestreamings/##channel##/schedules?filter[date]=##urldate2##',
  'requestOption2' => '1',
  'accept_header2' => '*/*',
  'content_type2' => 'application/vnd.api+json',
  'host_header2' => 'api.vidio.com',
  'origin_header2' => 'https://www.vidio.com',
  'custom_header2' => 'X-API-KEY: ##grabber_1##',
  'urldate_format2' => 'Y-m-d',
  'show' => '({"id":"\\d+","type":"schedule".*?}})',
  'start' => '"start_time":"(.*?)\\+',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"end_time":"(.*?)\\+',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"title":"(.*?)","',
  'desc' => '"description":"(.*?)","',
  'showicon' => '"image_landscape_url":"(.*?)"',
  'channel_logo' => '||#add#https://thumbor.prod.vidiocdn.com/##cclogo##||#replace#(____)||/64x64/filters:quality(70)/vidio-web-prod-livestreaming/uploads/livestreaming/square_image/',
  'ccurl1' => 'https://www.vidio.com/auth',
  'ccrequestOption1' => '2',
  'ccpost_data1' => ' ||#replace#(\\s)||',
  'ccaccept_header1' => '*/*',
  'cchost_header1' => 'www.vidio.com',
  'ccorigin_header1' => 'https://www.vidio.com',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '"api_key":"(.*?)"',
  'ccurl2' => 'https://api.vidio.com/livestreamings?stream_type=tv_stream',
  'ccrequestOption2' => '1',
  'ccaccept_header2' => '*/*',
  'cccontent_type2' => 'application/vnd.api+json',
  'cchost_header2' => 'api.vidio.com',
  'ccorigin_header2' => 'https://www.vidio.com',
  'cccustom_header2' => 'X-API-KEY: ##grabber_1##',
  'ccchannel_block' => '{"id":".*?}}',
  'ccchannel_id' => '"id":"(\\d+)',
  'ccchannel_name' => '"title":"(.*?)",',
  'ccchannel_logo' => '"url":".*?vidiocdn\\.com\\/(.*?)"||#replace#(\\/64x.*?square_image\\/)||____',
);
?>