<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'sportsnet.ca',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-04-02',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '8',
  'url1' => 'https://production-cdn.sportsnet.ca/api/schedules?channels=##channel##&date=##urldate1##&device=web_browser&duration=24&ff=idp%2Cldp%2Crpt%2Crgrs%2Ccd%2Cdpl&hour=0&intersect=true&lang=en&segments=',
  'requestOption1' => '1',
  'accept_header1' => 'application/json',
  'host_header1' => 'production-cdn.sportsnet.ca',
  'origin_header1' => 'https://watch.sportsnet.ca',
  'urldate_format1' => 'Y-m-d',
  'show' => '({"ContentId".*?}}})',
  'start' => '"startDate":"(.*?)Z',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"endDate":"(.*?)Z',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"title":"(.*?)",',
  'desc' => '"shortDescription":"(.*?)",',
  'showicon' => '"(?:tile|wallpaper)":"(.*?)\\&Width=||#addend#&Width=640&Height=480',
  'channel_logo' => '||#add#https://production-static.sportsnet-static.com/shain/v1/dataservice/ResizeImage/$value?Format=%27png%27&Quality=100&ImageId=%27##cclogo##%27&EntityType=%27Item%27&EntityId=%27##channel##%27&Width=120&Height=120',
  'ccurl1' => 'https://watch.sportsnet.ca/schedule/tvlistings',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'watch.sportsnet.ca',
  'ccchannel_block' => '{"images":{".*?"path":".*?}||#exclude#"title":"TV Listings"',
  'ccchannel_id' => '"id":"(.*?)"',
  'ccchannel_name' => '"title":"(.*?)"',
  'ccchannel_logo' => '"logo":".*?ImageId=\'(\\d+)',
);
?>