<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tvhebdo.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-05-26',
  'rev_no' => 'R0',
  'timezone' => 'America/Halifax',
  'culture' => 'en',
  'max_day' => '10',
  'episodeOption' => '1',
  'url1' => 'https://www.tvhebdo.com/horaire-tele/##channel##/date/##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=utf-8',
  'host_header1' => 'www.tvhebdo.com',
  'urldate_format1' => 'Y-m-d',
  'show' => '<tr class="liste_row_style_\\w+">(.*?)<\\/tr>',
  'start' => '<td class="heure">(\\d{2}[\\.:]\\d{2})',
  'start_format' => 'H#i',
  'title' => '<td class="titre">(.*?)<\\/td>',
  'channel_logo' => '||#add#https://www.tvhebdo.com/uploads/logos_stations/##cclogo##',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'https://www.tvhebdo.com##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html, */*; q=0.01',
  'detail_content_type1' => 'text/html; charset=utf-8',
  'detail_host_header1' => 'www.tvhebdo.com',
  'detail_XMLHttpRequest1' => 'on',
  'detail_duration' => '<h4>.*?-\\s*(\\d+) min||#format#m',
  'detail_title' => '<div id="dd_header_left">(.*?)(?:-\\s.*?)?<\\/div>',
  'detail_subtitle' => '<div id="dd_header_left">(.*?)<\\/div>||#replace#^(.*?-\\s)||',
  'detail_desc' => '<p id="dd_desc">(.*?)<\\/p>||#replace#(\\((?:S\\d+)?(?:EP\\d+)?\\))||',
  'detail_category' => '<h4>(.*?)-',
  'detail_showicon' => '<img src="(.*?)"||#addstart#https://www.tvhebdo.com',
  'detail_season' => ' <p id="dd_desc">\\s*\\(S(?:0+)?(\\d+)|Saison (\\d+)',
  'detail_episode' => ' <p id="dd_desc">\\s*\\((?:S(?:0+)?\\d+)?EP(?:0+)?(\\d+)|Épisode (\\d+)',
  'detail_production_date' => '<h4>.*?-\\s*\\d+ min -.*?-\\s(\\d{4})',
  'detail_actor' => 'Avec: <br \\/>(.*?)<br \\/><br \\/>||#split#(<br \\/>)||#replace#(\\s\\(.*?\\))||',
  'detail_role' => 'Avec: <br \\/>(.*?)<br \\/><br \\/>||#split#(<br \\/>)||#replace#^(.*?\\s\\()##(\\))$||##',
  'detail_director' => 'Réalisation: <br \\/>(.*?)<br \\/><br \\/>||#split#(<br \\/>)',
  'detail_writer' => 'Scénario : <br \\/>(.*?)<br \\/><br \\/>||#split#(<br \\/>)',
  'detail_country' => '<h4>.*?-\\s*\\d+ min -\\s*([A-Z]+)\\s',
  'detail_premiere' => '<h4>.*?-\\s*(PRIMEUR)||#replace#(PRIMEUR)||true',
  'ccurl1' => 'https://www.tvhebdo.com/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=utf-8',
  'cccookie_jar1' => 'on',
  'ccurl2' => 'www.tvhebdo.com/horaire/gr/offset/20/gr_id/##subpage2##/date/##urldate2##/time/00:00:00||#calc#offset\\/(20)\\/||*##subpage2##',
  'ccrequestOption2' => '1',
  'ccaccept_header2' => '*/*',
  'cccontent_type2' => 'application/x-www-form-urlencoded',
  'cchost_header2' => 'www.tvhebdo.com',
  'ccXMLHttpRequest2' => 'on',
  'cccookie_jar2' => 'on',
  'ccurldate_format2' => 'Y-m-d',
  'ccsubpage_format2' => '0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18',
  'ccchannel_block' => '<div class="gr_row_head_cont">.*?<\\/a>',
  'ccchannel_id' => 'href="\\/horaire-tele\\/(.*?)"',
  'ccchannel_name' => '<img alt="(.*?)"',
  'ccchannel_logo' => 'logos_stations\\/(.*?)"',
);
?>