<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'beinsports.com.tr',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-01-14',
  'rev_no' => 'R0',
  'timezone' => '+03:00',
  'culture' => 'tr',
  'max_day' => '1',
  'url1' => 'https://beinsports.com.tr/yayin-akisi',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'beinsports.com.tr',
  'static_url1' => 'on',
  'grabber_1' => 'on',
  'gpattern_1' => '"buildId":\\s*"(\\d+)',
  'url2' => 'https://beinsports.com.tr/_next/data/##grabber_1##/tr-TR/yayin-akisi/##channel##/##urldate2##.json?rewriteIds=##channel##&rewriteIds=##urldate2##',
  'requestOption2' => '1',
  'accept_header2' => '*/*',
  'host_header2' => 'beinsports.com.tr',
  'custom_header2' => 'X-Nextjs-Data: 1',
  'urldate_format2' => '#weekdayname#pazartesi|sali|carsamba|persembe|cuma|cumartesi|pazar',
  'show' => '({"channel_id":.*?})',
  'start' => '"event_time":"(.*?)"',
  'start_format' => 'H#i#s',
  'title' => '"name":"(.*?)",',
  'channel_logo' => '{"rewriteId":"##channel##","image":"(.*?)"',
  'ccurl1' => 'https://beinsports.com.tr/yayin-akisi',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'beinsports.com.tr',
  'ccchannel_block' => '"activeLeagues":\\[.*?(?:{)(.*?)(?:}).*?\\]',
  'ccchannel_id' => '"rewriteId":"(.*?)"',
  'ccchannel_name' => '"rewriteId":"(.*?)"||#replace#(-)|| ||#word#',
);
?>