<?php return array (
  'filename' => 'showturk.com.tr',
  'creator_name' => 'Kivanc',
  'creation_date' => '30.07.2019',
  'rev_no' => 'R0',
  'timezone' => '+03:00',
  'culture' => 'tr',
  'max_day' => '7.1',
  'first_day' => '0123456',
  'url1' => 'http://www.showturk.com.tr/yayin-akisi',
  'requestOption1' => '1',
  'show' => '<div id="timelineDailyData.*?(?:<ul class)(.*?)(?:<\\/ul>).*?<\\/div>',
  'start' => '<li class="saat">.*?>(.*?)<\\/li>',
  'start_format' => 'H#i',
  'title' => '<span class="yayin_adi">(.*?)(?:\\s-\\s.*?)?<\\/span>',
  'desc' => '<span class="yayin_adi">(?:.*?\\s-\\s)(.*?)<\\/span>',
  'showicon' => '<li class="image">.*?src="(.*?)"',
  'channel_logo' => '||#add#http://www.showturk.com.tr/images/core/showturk_logo.png?v=7',
  'ccrequestOption1' => '1',
  'ccchannel_id' => '||#set#showturk',
  'ccchannel_name' => '||#set#Show Türk',
);
