<?php return array (
  'filename' => 'showmax.com.tr',
  'creator_name' => 'Kivanc',
  'creation_date' => '30.07.2019',
  'rev_no' => 'R0',
  'timezone' => '+03:00',
  'culture' => 'tr',
  'max_day' => '7.1',
  'first_day' => '0123456',
  'url1' => 'http://www.showmax.com.tr/yayin-akisi',
  'requestOption1' => '1',
  'show' => '<div id="timelineDailyData.*?(?:<a)(.*?)(?:<\\/a>).*?<\\/div>',
  'start' => '<li class="saat">.*?>(.*?)<\\/li>',
  'start_format' => 'H#i',
  'title' => '<span class="yayin_adi">(.*?)<\\/span>',
  'showicon' => '<li class="image">.*?src="(.*?)"',
  'channel_logo' => '||#add#http://www.showmax.com.tr/images/core/showmax_logo.png?v=12',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'http://www.showmax.com.tr/##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_desc' => '<div class="program-info">(.*?)<\\/div>',
  'ccrequestOption1' => '1',
  'ccchannel_id' => '||#set#showmax',
  'ccchannel_name' => '||#set#Show Max',
);
