<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tivilife.com.tr',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-06-25',
  'rev_no' => 'R0',
  'timezone' => '+03:00',
  'culture' => 'tr',
  'max_day' => '7',
  'url1' => 'https://tivilife.com.tr/yayin-akisi',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cookie_jar1' => 'on',
  'static_url1' => 'on',
  'grabber_1' => 'on',
  'gpattern_1' => '.*"__RequestVerificationToken" type="hidden" value="(.*?)"',
  'url2' => 'https://tivilife.com.tr/Asset/GetTvGuide/',
  'requestOption2' => '2',
  'post_data2' => 'date=##urldate2##&__RequestVerificationToken=##grabber_1##',
  'accept_header2' => '*/*',
  'content_type2' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'origin_header2' => 'https://tivilife.com.tr',
  'XMLHttpRequest2' => 'on',
  'cookie_jar2' => 'on',
  'urldate_format2' => 'd.m.Y',
  'show' => '(<div class="row">.*?<\\/div>\\s*<\\/div>)',
  'start' => '<b style="color:white">\\s*(\\d+[\\.:]\\d+)',
  'start_format' => 'H#i',
  'title' => '.*style="color:white">(.*?)<\\/||#word#',
  'showicon' => '<img src="(http.*?)"',
  'channel_logo' => '||#add#https://tivilife.com.tr/content/logo/tivilife.png?v=1.0.0.73',
  'pagekey1' => '<a href="(.*?)"',
  'detail_url1' => 'https://tivilife.com.tr##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_cookie_jar1' => 'on',
  'detail_title_original' => '<span class="fl-title-medium">(.*?)(?:\\s\\(.*?\\))?<\\/||#culture#en',
  'detail_desc' => '<p>\\s*(.*?)\\s*<\\/p>',
  'detail_showicon' => '<img src="(http.*?)"',
  'detail_production_date' => '\\s\\((\\d{4})\\)\\s*<\\/span>',
  'ccrequestOption1' => '1',
  'ccchannel_id' => '||#set#tivilife',
  'ccchannel_name' => '||#set#Tivilife',
);
?>