<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tv.vera.com.uy',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-12-20',
  'rev_no' => 'R0',
  'remarks' => 'Kept unlocked to demonstrate Tempest\'s skills',
  'timezone' => 'America/Montevideo',
  'culture' => 'es',
  'max_day' => '7.1',
  'url1' => 'https://veratv-be.vera.com.uy/api/sesiones',
  'requestOption1' => '2',
  'post_data1' => '{"tipo":"anonima"}',
  'accept_header1' => 'application/json',
  'content_type1' => 'application/json',
  'host_header1' => 'veratv-be.vera.com.uy',
  'origin_header1' => 'https://tv.vera.com.uy',
  'custom_header1' => 'X-Forwarded-For',
  'grabber_1' => 'on',
  'gpattern_1' => '"jwt":"(.*?)"',
  'grabber_2' => 'on',
  'gpattern_2' => '"token":"(.*?)"',
  'url2' => 'https://cds-frontend.vera.com.uy/api-contenidos/canales/epg/##channel##?limit=1000&dias_siguientes=##stopdate2##&fecha=##urldate2##&token=##grabber_2##',
  'requestOption2' => '1',
  'accept_header2' => 'application/json, text/plain, */*',
  'content_type2' => 'application/json',
  'host_header2' => 'cds-frontend.vera.com.uy',
  'origin_header2' => 'https://tv.vera.com.uy',
  'custom_header2' => 'authorization: Bearer ##grabber_1##|#|x-frontend-id: ##grabber_3##|#|x-service-id: ##grabber_4##|#|x-system-id: 1',
  'urldate_format2' => 'Y-m-d',
  'stopdate_format2' => '#daycounter#0',
  'grabber_3' => 'on',
  'gpattern_3' => '"id_frontend":(\\d+)||#url1#',
  'grabber_4' => 'on',
  'gpattern_4' => '"id_servicio":(\\d+)||#url1#',
  'show' => '({"id":.*?"canal_public_id":.*?})',
  'start' => '"fecha_hora_inicio":"(.*?)"',
  'start_format' => 'Y-m-d H#i#s',
  'stop' => '"fecha_hora_fin":"(.*?)"',
  'stop_format' => 'Y-m-d H#i#s',
  'title' => '"nombre_programa":"(.*?)",',
  'subtitle' => '"subtitle":"(.*?)",',
  'desc' => '"descripcion":"(.*?)",|>|"descripcion_corta":"(.*?)",',
  'channel_logo' => '||#add#https://cds-assets.cdn.antel.net.uy/imagenes/recursos/##cclogo##.jpeg',
  'ccurl1' => 'https://veratv-be.vera.com.uy/api/sesiones',
  'ccrequestOption1' => '2',
  'ccpost_data1' => '{"tipo":"anonima"}',
  'ccaccept_header1' => 'application/json',
  'cccontent_type1' => 'application/json',
  'cchost_header1' => 'veratv-be.vera.com.uy',
  'ccorigin_header1' => 'https://tv.vera.com.uy',
  'cccustom_header1' => 'X-Forwarded-For',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '"jwt":"(.*?)"',
  'ccgrabber_2' => 'on',
  'ccgpattern_2' => '"token":"(.*?)"',
  'ccurl2' => 'https://cds-frontend.vera.com.uy/api-contenidos/canales/epg?limit=1000&dias_previos=0&dias_siguientes=1&fecha=##urldate2##&autocompletar_grilla=true&token=##grabber_2##',
  'ccrequestOption2' => '1',
  'ccaccept_header2' => 'application/json, text/plain, */*',
  'cccontent_type2' => 'application/json',
  'cchost_header2' => 'cds-frontend.vera.com.uy',
  'ccorigin_header2' => 'https://tv.vera.com.uy',
  'cccustom_header2' => 'authorization: Bearer ##grabber_1##|#|x-frontend-id: ##grabber_3##|#|x-service-id: ##grabber_4##|#|x-system-id: 1',
  'ccurldate_format2' => 'Y-m-d',
  'ccgrabber_3' => 'on',
  'ccgpattern_3' => '"id_frontend":(\\d+)||#url1#',
  'ccgrabber_4' => 'on',
  'ccgpattern_4' => '"id_servicio":(\\d+)||#url1#',
  'ccchannel_block' => '{"id":\\d+,"sync_date.*?}}',
  'ccchannel_id' => '"public_id":"(.*?)"',
  'ccchannel_name' => '"nombre":"(.*?)","nombre_corto',
  'ccchannel_logo' => '"imagen_principal":"\\S+\\/recursos\\/(.*?)\\.jpeg',
);
?>