<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'clickthecity.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-06-19',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Manila',
  'culture' => 'en',
  'max_day' => '10',
  'rating_system' => 'MTRCB',
  'episodeOption' => '1',
  'url1' => 'https://www.clickthecity.com/tv/channels/?netid=##channel##',
  'requestOption1' => '2',
  'post_data1' => 'optDate=##urldate1##&optTime=00%3A00%3A00&btnLoad=Go',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'content_type1' => 'application/x-www-form-urlencoded',
  'host_header1' => 'www.clickthecity.com',
  'origin_header1' => 'https://www.clickthecity.com',
  'urldate_format1' => 'Y-m-d',
  'show' => '(<tr>.*?<\\/tr>)||#exclude#<script',
  'start' => 'cTme.*?>(.*?)<',
  'start_format' => 'h:i a',
  'title' => '"cPrg.*?>(.*?)<\\/a>||#replace#(\\s\\(Season.*?\\)(?:\\s*)?)||',
  'season' => '\\(Season (\\d+)',
  'channel_logo' => '<img class="lazyload" data-src="(.*?)"',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => 'https://www.clickthecity.com##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_host_header1' => 'www.clickthecity.com',
  'detail_desc' => '<div class="more synopsis">(.*?)<\\/div>',
  'detail_category' => 'itemprop="genre">(.*?)<\\/',
  'detail_showicon' => 'ImageObject">\\s*<a class="" href="(.*?)"',
  'detail_production_date' => '<span class="fw-normal.*?>(\\d{4})',
  'detail_actor' => '<\\/div><span itemprop="name">(.*?)<\\/span>',
  'detail_role' => 'secondary text-wrap">(.*?)<\\/span>',
  'detail_director' => '<span itemprop="director" itemscope.*?>(?:<a.*?><span.*?>)?(.*?)<\\/span>',
  'detail_producer' => '<span itemprop="productionCompany">(.*?)<\\/span>',
  'detail_writer' => '<span itemprop="author" itemscope.*?>(?:<a.*?><span.*?>)?(.*?)<\\/span>',
  'detail_rating' => 'itemprop="contentRating">(.*?)<',
  'detail_star_rating' => '"ratingValue">(\\d+(?:\\.\\d+)?)||#addend#/5',
  'ccurl1' => 'https://www.clickthecity.com/tv/channels/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'www.clickthecity.com',
  'ccchannel_block' => '<div class="col">.*?<\\/div>',
  'ccchannel_id' => 'netid=(\\d+)',
  'ccchannel_name' => 'alt="(.*?)"',
);
?>