<?php return array (
  'filename' => 'mytv.com.vn',
  'creator_name' => 'Kivanc',
  'creation_date' => '2021-09-18',
  'rev_no' => 'R0',
  'timezone' => '+07:00',
  'culture' => 'vi',
  'max_day' => '10',
  'url1' => 'https://mytv.com.vn/lich-phat-song?ddlKenhLPSKenh=##channel##&from=##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html; charset=UTF-8',
  'host_header1' => 'mytv.com.vn',
  'urldate_format1' => 'd-m-Y',
  'show' => '<select class="form-control form-control-lg".*?(?:<tr>)(.*?)(?:<\\/tr>).*?<div class="clearfix">||#exclude#Thời gian#col-xs-3"></td>',
  'start' => '<td class="col-xs-3">(?:\\s+)?(\\d{2}[\\.:]\\d{2})',
  'start_format' => 'H#i',
  'title' => '<td class="col-xs-9">(.*?)<\\/td>',
  'ccurl1' => 'https://mytv.com.vn/lich-phat-song',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'cchost_header1' => 'mytv.com.vn',
  'ccchannel_block' => '<select name="ddlKenhLPSKenh".*?(?:<option)(.*?)(?:<\\/option>).*?<\\/select>',
  'ccchannel_id' => 'value="(\\d+)',
  'ccchannel_name' => '>(.*?)$',
);
?>