<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'media.foxsports.com.au',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-11-09',
  'rev_no' => 'R0',
  'timezone' => 'Australia/Sydney',
  'culture' => 'en',
  'max_day' => '7.1',
  'rating_system' => 'NCS',
  'episodeOption' => '1',
  'url1' => 'https://tvguide.foxsports.com.au/granite-api/programmes.json?from=##urldate1##&to=##stopdate1##&channel=##channel##&&callback=handleTvGuide',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'host_header1' => 'tvguide.foxsports.com.au',
  'urldate_format1' => 'Y-m-d',
  'stopdate_format1' => 'Y-m-d',
  'show' => '({\\s*"id".*?})',
  'start' => '"startTime":\\s*"(.*?)\\+',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"endTime":\\s*"(.*?)\\+',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"programmeTitle":\\s*"(.*?)",|#|[| - |]"title":\\s*"(.*?)",',
  'desc' => '"synopsis":\\s*"(.*?)",',
  'category' => '"genreTitle":\\s*"(.*?)",|#|"(live)":\\s*true',
  'episode' => 'Episode\\s(\\d+)',
  'videoaspect' => '"widescreen":\\s*(true),||#replace#(true)||16:9',
  'videoquality' => '"hiDef":\\s*(true),||#replace#(true)||HD',
  'subtitles' => '"closedCaptioned":\\s*(true),',
  'rating' => '"classification":\\s*"(.*?)",',
  'ccurl1' => 'https://media.foxsports.com.au/technology/resources/prod/tv-guide/1.0.0/tv-guide.noflash.html',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'media.foxsports.com.au',
  'ccchannel_block' => '"channel">.*?.*?<\\/select>',
  'ccchannel_id' => 'value="(?!0)(\\d+)',
  'ccchannel_name' => 'value="(?!0)\\d+".*?>(.*?)<\\/',
);
?>