<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'sport.optus.com.au',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-12-30',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '7.1',
  'episodeOption' => '1',
  'url1' => 'https://epg.optusvideo.tv/api/channels/##channel##?mergeAttrs=true',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'host_header1' => 'epg.optusvideo.tv',
  'origin_header1' => 'https://sport.optus.com.au',
  'show' => '({"id":"\\d+","name".*?"ContentDescriptor":.*?(?:"SessionType".*?}|}}))',
  'start' => '"start":"(.*?)"',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"stop":"(.*?)"',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"name":"(.*?)",',
  'subtitle' => '"EventName":{"_":"(.*?)",',
  'desc' => '"Text":{"_":"(.*?)","',
  'category' => ',"SessionType":"(.*?)"',
  'episode' => '"Item":{"_":"(\\d+)","description":"Episode Number"',
  'channel_logo' => '||#add#https://static.sport.optus.com.au/resources/static/##cclogo##',
  'ccurl1' => 'https://static.sport.optus.com.au/api/metadata/editorials/v2/home_linear_channels/web',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cchost_header1' => 'static.sport.optus.com.au',
  'ccorigin_header1' => 'https://sport.optus.com.au',
  'ccchannel_block' => '"channel":{"id":".*?"imageSource"',
  'ccchannel_id' => '"channel":{"id":"(.*?)"',
  'ccchannel_name' => '"seoTitle":"(.*?)"',
  'ccchannel_logo' => '\\/resources\\/static\\/(.*?)"',
);
?>
