<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => '7tvandalucia.e',
  'creator_name' => 'Kivanc',
  'creation_date' => '2024-05-23',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Madrid',
  'culture' => 'es',
  'max_day' => '7.1',
  'first_day' => '0123456',
  'url1' => 'https://7tvandalucia.es/##channel##/programacion/',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => '7tvandalucia.es',
  'show' => '<!-- DIA\\s*:.*?(?:<li class="cd-schedule__event ">)(.*?)(?:<\\/li>).*?<!--\\s*\\/\\/\\s*DIA',
  'start' => 'data-start="(\\d+[\\.:]\\d+)',
  'start_format' => 'H#i',
  'stop' => 'data-end="(\\d+[\\.:]\\d+)',
  'stop_format' => 'H#i',
  'title' => '<em class=".*?">(.*?)<\\/em>',
  'channel_logo' => '||#add#https://7tvandalucia.es/docs/img/logo7TV.svg?##channel##',
  'pagekey1' => 'data-content="(?!0)(\\d+)',
  'detail_url1' => 'https://7tvandalucia.es/docs/programacion-datos-programa.php?id=##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => '*/*',
  'detail_host_header1' => '7tvandalucia.es',
  'detail_desc' => 'DESCRIPCIÓN ABREVIADA -->.*?<p>(.*?)<\\/p>',
  'detail_category' => '<h6 class.*?>(.*?)<\\/h6>',
  'detail_presenter' => '<strong class="text-gray-100"><p>(.*?)<\\/p>',
  'ccurl1' => 'https://7tvandalucia.es/aljarafe/programacion/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => '7tvandalucia.es',
  'ccchannel_block' => 'id="SelectCanal\\s*".*?>\\s*.*?\\s*<\\/select>',
  'ccchannel_id' => '<option value="(.*?)"||#replace#(https:\\/\\/.*?\\/)##(\\/)||##',
  'ccchannel_name' => '<option value=".*?>(.*?)<\\/option>',
);
?>