<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'bomcine.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-08-05',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Madrid',
  'culture' => 'es',
  'max_day' => '7.1',
  'rating_system' => 'ICAA',
  'url1' => 'https://bomcine.com/programacion',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'bomcine.com',
  'cookie_jar1' => 'on',
  'url2' => 'https://bomcine.com/php/getSchedule.php',
  'requestOption2' => '2',
  'post_data2' => 'days=##stopdate2##',
  'accept_header2' => 'application/json, text/javascript, */*; q=0.01',
  'content_type2' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'host_header2' => 'bomcine.com',
  'origin_header2' => 'https://bomcine.com',
  'XMLHttpRequest2' => 'on',
  'cookie_jar2' => 'on',
  'stopdate_format2' => '#daycounter#1',
  'show' => '(<div id=\\\\"item_.*?)\\s*"iconify\\\\"',
  'start' => 'id="showDate" value="(.*?)"',
  'start_format' => 'M d, H#i',
  'title' => '"showTitle" value="(.*?)">',
  'desc' => '"showText" value="(.*?)">',
  'showicon' => '"showIMG" value="(.*?)">||#addstart#https://bomcine.com/img/films/',
  'channel_logo' => '||#add#https://web.squirrelmedia.es/img/ico/logo_bomcine_v2.svg',
  'pagekey1' => '"showURL" value="(.*?)"',
  'detail_url1' => 'https://bomcine.com/##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => ' text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_referer_header1' => ' https://bomcine.com/programacion',
  'detail_host_header1' => 'bomcine.com',
  'detail_cookie_jar1' => 'on',
  'detail_category' => '<p class="pDato"><strong>\\s*\\d{4}\\s*(.*?)<\\/strong>||#split#(,)',
  'detail_production_date' => '<p class="pDato"><strong>\\s*(\\d{4})',
  'detail_actor' => '<p class="pDato"><strong>Reparto\\s*<\\/strong>(.*?)<\\/p>||#split#(,)||#replace#(\\.+(?:\\s*)?)$||',
  'detail_director' => '<p class="pDato"><strong>Director\\s*<\\/strong>(.*?)<\\/p>||#split#(,)',
  'detail_rating' => '<p class="pLast">.*?\\((.*?)\\)\\s*<\\/p>',
  'ccrequestOption1' => '1',
  'ccchannel_id' => '||#set#bom-cine-tv',
  'ccchannel_name' => '||#set#BOM cine TV',
);
?>