<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'vodafone.es',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-06-01',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Madrid',
  'culture' => 'es',
  'max_day' => '4',
  'rating_system' => 'ICAA',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'https://vodafone-epg-info.s3.eu-central-1.amazonaws.com/##urldate1##.json',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'content_type1' => 'text/plain',
  'host_header1' => 'vodafone-epg-info.s3.eu-central-1.amazonaws.com',
  'origin_header1' => 'https://www.vodafone.es',
  'urldate_format1' => 'Ymd',
  'show' => '"##channel##":\\[.*?(?:{)(.*?"tv_rating":".*?)(?:}).*?\\]||#replace#(.*?"schedule_air_time":"\\d{3}".*?)$||xxDELETEDxx||#exclude#xxDELETEDxx',
  'start' => '"schedule_air_date":"(\\d+)|#|[| |]"schedule_air_time":"(\\d+)',
  'start_format' => 'Ymd Hi',
  'duration' => '"schedule_duration":"(\\d+)||#format#m',
  'title' => '"title":"(.*?)",',
  'desc' => '"program_desc":"(.*?)",|#|[|___|]"title":"(.*?)",||#replace#^(.*?)___\\1##(___.*?)$||##',
  'category' => '"show_type":"(.*?)",|#|"genres":"(.*?)"||#replace#([a-z])([A-Z])||\\1,\\2||#split#(,)',
  'season' => '"season_number":"(?!0)(\\d+)',
  'episode' => '"episode_number":"(?!0)(\\d+)',
  'channel_logo' => '||#add#https://www.vodafone.es/c/microsite/1500009248080/img/##channel##.png',
  'production_date' => '"year":"(\\d{4})',
  'rating' => '"tv_rating":"(?!0)(\\d+)',
  'ccurl1' => 'https://vodafone-epg-info.s3.eu-central-1.amazonaws.com/sta.json',
  'ccrequestOption1' => '1',
  'cccontent_type1' => 'application/json',
  'ccchannel_block' => '(?:{|,)"\\d+":{.*?}',
  'ccchannel_id' => '(?:{|,)"(\\d+)":',
  'ccchannel_name' => '"name":"(.*?)"',
);
?>