<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'delta.nl',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-05-23',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'nl',
  'max_day' => '9.1',
  'rating_system' => 'kijkwijzer',
  'url1' => 'https://clientapi.tv.delta.nl/guide/channels/list?start=##urldate1##&end=##stopdate1##&includeDetails=true&channels=##channel##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'application/json;charset=UTF-8',
  'host_header1' => 'clientapi.tv.delta.nl',
  'urldate_format1' => 'unix',
  'stopdate_format1' => 'unix',
  'show' => '({\\s*"ID":.*?"isFiller".*?})',
  'start' => '"start": (\\d+)',
  'start_format' => 'unix',
  'stop' => '"end": (\\d+)',
  'stop_format' => 'unix',
  'title' => '"title": "(.*?)",',
  'showicon' => '"url": "(.*?)"',
  'channel_logo' => '||#add#https://live-delta.ottnow.stoneroos.com/image/logo/tv.delta.nl/assets/graphics/thumbnails/channel/delta/##cclogo##.svg',
  'rating' => '"kijkwijzer": \\[\\s*"(.*?)"\\s*\\]||#replace#(",\\s*")|| | ',
  'pagekey1' => '"ID": "(.*?)"',
  'detail_url1' => 'https://clientapi.tv.delta.nl/guide/4/details/##pagekey1##?X-Response-Version=4.5',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'application/json;charset=UTF-8',
  'detail_host_header1' => 'clientapi.tv.delta.nl',
  'detail_desc' => '"description": "(.*?)",',
  'ccurl1' => 'https://clientapi.tv.delta.nl/channels/list',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cchost_header1' => 'clientapi.tv.delta.nl',
  'ccchannel_block' => '{\\s*"ID":.*?}',
  'ccchannel_id' => '"epgID": "(\\d+)',
  'ccchannel_name' => '"name": "(.*?)",',
  'ccchannel_logo' => '"logo":.*?\\/channel\\/delta\\/(.*?)\\.',
);
?>