<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tvgids.nl',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-11-20',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'nl',
  'max_day' => '6',
  'rating_system' => 'Kijkwijzer',
  'episodeOption' => '1',
  'url1' => 'https://www.tvgids.nl/gids/##urldate1##__##stopdate1##__/##channel##||#replace#(gids)\\/.*?__1__##__(?!1)\\d+__||\\1##',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'content_type1' => 'text/html',
  'host_header1' => 'www.tvgids.nl',
  'urldate_format1' => 'd-m-Y',
  'stopdate_format1' => '#daycounter#0',
  'show' => '(<a  href="\\/.*?<\\/a>)',
  'start' => 'data-start="(\\d+)',
  'start_format' => 'unix',
  'stop' => 'data-eind="(\\d+)',
  'stop_format' => 'unix',
  'title' => '<h3 class="program__title">(.*?)<\\/h3>',
  'desc' => '<p class="program__text">(.*?)<\\/p>||#addend#\\n##detail##',
  'category' => 'label--live">(live)<\\/span>|#|<a  href="\\/(.*?)\\/||#addend#,##detail##||#split#(,)||#word#',
  'showicon' => 'data-src="(.*?)"||#replace#(\\/klein)||',
  'channel_logo' => '<div class="guide__channel-logo guide__channel-active">\\s*<img data-src="(.*?)"',
  'pshown' => 'label--(rerun)">',
  'pagekey1' => '<a  href="(.*?)"',
  'detail_url1' => 'https://www.tvgids.nl##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html',
  'detail_host_header1' => 'www.tvgids.nl',
  'detail_desc' => 'detailpage__intro-overlay">(.*?)<\\/div>|#|[|\\n|]<div class="seoblock">(.*?)<\\/div>',
  'detail_category' => '"genre": "(.*?)"|>|itemprop="genre">(.*?)<\\/p>',
  'detail_season' => '"numberOfSeasons": "(\\d+)',
  'detail_production_date' => 'itemprop="firstRelease">\\s*(\\d{4})',
  'detail_actor' => '"\\@type": "Person","name": "(.*?)"}||#max#10',
  'detail_director' => '"director": "(.*?)"||#split#(,)',
  'detail_premiere' => '"datePublished": "(\\d{4})',
  'detail_subtitles' => 'Ondertiteling<\\/h3>\\s*<p class="table__value">\\s*(Ja)',
  'detail_rating' => 'Kijkwijzer<\\/h3>\\s*<div class="table__value">\\s*(.*?)<\\/div>||#replace#.*?alt="(.*?)".*?<\\/object>\\s*##(\\s\\|\\s$)||\\1 \\| ##',
  'ccurl1' => 'https://www.tvgids.nl/gids/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html',
  'cchost_header1' => 'www.tvgids.nl',
  'ccchannel_block' => '<li data-chbar=.*?<\\/li>',
  'ccchannel_id' => ' id="(.*?)"',
  'ccchannel_name' => 'title="(.*?)">',
);
?>