<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'ziggosport.nl',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-10-27',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'nl',
  'max_day' => '8',
  'keepindexpage' => 'on',
  'url1' => 'https://www.ziggosport.nl/cache/site/ZiggosportNL/json/epg/epg-##urldate1##.json',
  'requestOption1' => '1',
  'accept_header1' => 'application/json',
  'content_type1' => 'application/json',
  'urldate_format1' => 'Y-m-d',
  'show' => '{"channel":"##channel##",.*?"programming":\\[.*?(?:{)(.*?)(?:}).*?\\]}',
  'start' => '"dateStart":"(.*?)\\+',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"dateEnd":"(.*?)\\+',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"title":"(.*?)","',
  'desc' => '"description":"(.*?)",',
  'category' => '"(live)":true,|#|,"sportName":"(.*?)"||#word#',
  'channel_logo' => '||#add#https://www.ziggosport.nl/images/logos/##cclogo##',
  'ccurl1' => 'https://www.ziggosport.nl/programmagids/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'ccchannel_block' => '<div class="tv-guide__list__item".*?<\\/a>',
  'ccchannel_id' => 'data-channel="(.*?)"',
  'ccchannel_name' => 'data-channel="(.*?)"',
  'ccchannel_logo' => 'src=".*?\\/logos\\/(.*?)"',
);
?>