<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'bbcbenelux.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-05-17',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'nl',
  'max_day' => '60',
  'episodeOption' => '1',
  'url1' => 'https://www.bbcbenelux.com/smapi/schedule/benelux/##channel##?timezone=Europe%2FLuxembourg&date=##urldate1##',
  'requestOption1' => '1',
  'content_type1' => 'application/json; charset=utf-8',
  'urldate_format1' => 'Y-m-d',
  'show' => '({.*?}}})',
  'start' => '"start":"(.*?)",',
  'start_format' => 'Y-m-d H#i#s',
  'stop' => '"end":"(.*?)",',
  'stop_format' => 'Y-m-d H#i#s',
  'title' => '"title":"(.*?)","',
  'subtitle' => '"episode":{.*?"title":"(.*?)","||#replace#((?:\\s)?(?:[Ss]eri(?:a|e)(?:s)?|[Ee]pisode|[Oo]dc\\.|[Aa]flevering)\\s\\d+(?:,)?)||',
  'desc' => '"episode":{.*?"synopsis":"(.*?)","|>|"synopsis":"(.*?)","||#replace#(\\s\\d+(?:\\/\\d+)?)$||',
  'season' => '"series":{.*?"number":(\\d+)',
  'episode' => '"episode":{.*?"number":(\\d+)',
  'episode_total' => '"episode":{.*?"synopsis":".*?\\.\\s\\d+\\/(\\d+)","',
  'channel_logo' => '||#add#https://www.bbcbenelux.com/_next/static/media/patch-200##cclogo##',
  'ccurl1' => 'https://www.bbcbenelux.com/tv-gids',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=utf-8',
  'ccchannel_block' => '<div class="form-field.*?<\\/div>',
  'ccchannel_id' => 'name="(.*?)"',
  'ccchannel_name' => '<label.*?>(.*?)<\\/label>',
  'ccchannel_logo' => '||#set#-neutral.251b5a785b0dde02db76db165a147d30.jpg|.6890b3ed54f1c871de9d33e833ef3164.png|.171d4ea9127fa564fb88e945d24b9d51.png|.8aba4a901b264afc441790b0ca2f2efd.png|.45d99ea0f0e57086bc021ae48fe75107.png|.61a0df82c92c435f9dc24ef856d4c08c.jpg|.e758c4bc2a0145c134c858f03427b90d.png',
);
?>