<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'directvsports.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-08-12',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'es',
  'max_day' => '7.1',
  'rating_system' => 'MPAA',
  'url1' => 'https://epg.tbxapis.com/v0/epg/external/entries',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'host_header1' => 'epg.tbxapis.com',
  'show' => '({"Title".*?})||#include#"ChannelNum":"##channel##"',
  'sort' => '"StartDate":"(.*?)\\+',
  'sortflag' => '1',
  'sortorder' => '1',
  'start' => '"StartDate":"(.*?)\\+',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"EndDate":"(.*?)\\+',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"Title":"(.*?)",',
  'desc' => '"Description":"(.*?)",',
  'category' => '"Is(Live)":"Y"|#|"Category":"(.*?)",|#|"SubCategory":"(.*?)",||#split#(,)',
  'channel_logo' => '||#add#https://dsports-widgets.tbxnet.com/assets/images/channels/##channel##.png',
  'videoquality' => '"Is(HD)":"Y"',
  'pshown' => '"Is(Repeat)":"Y"',
  'rating' => '"Rating":"(.*?)"',
  'ccurl1' => 'https://epg.tbxapis.com/v0/epg/external/entries',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => '*/*',
  'cchost_header1' => 'epg.tbxapis.com',
  'ccchannel_block' => '{"ChannelNumber".*?}',
  'ccchannel_id' => '"ChannelNumber":"(\\d+)',
  'ccchannel_name' => '"ChannelName":"(.*?)",',
);
?>