<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'magticom.ge',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-06-30',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Tbilisi',
  'culture' => 'ka',
  'max_day' => '7.1',
  'url1' => 'https://www.magticom.ge/request/channel-program.php',
  'requestOption1' => '2',
  'post_data1' => 'channelId=##channel##&start=##urldate1##&end=##stopdate1##',
  'accept_header1' => '*/*',
  'content_type1' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'referer_header1' => 'https://www.magticom.ge/en/tv/tv-services/tv-guide',
  'origin_header1' => 'https://www.magticom.ge',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'unix',
  'stopdate_format1' => 'unix',
  'show' => '({"id":.*?"longInfo":.*?})',
  'start' => '"startTimestamp":"(.*?)"',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"endTimestamp":"(.*?)"',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"title":"(.*?)","',
  'subtitle' => '"subTitle":"(.*?)","',
  'desc' => '"longInfo":"(.*?)"|>|"info":"(.*?)","',
  'language' => '"nameShort":"(.*?)"',
  'channel_logo' => '||#add#https://www.magticom.ge/images/channels/##cclogo##.jpg',
  'ccurl1' => 'https://www.magticom.ge/en/tv/tv-services/tv-guide',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'ccchannel_block' => '<div class="tv-guide-channel bottom-line hidden".*?<\\/div><\\/div>',
  'ccchannel_id' => ' data-id="(\\d+)',
  'ccchannel_name' => ' alt="(.*?)"',
  'ccchannel_logo' => '"images\\/channels\\/(.*?)"',
);
?>