<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'myvideo.ge',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-03-25',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Tbilisi',
  'culture' => 'ka',
  'max_day' => '5.1',
  'url1' => 'https://api.myvideo.ge/api/v1/auth/token',
  'requestOption1' => '2',
  'post_data1' => 'client_id=7&grant_type=client_implicit',
  'accept_header1' => 'application/json, text/plain, */*',
  'content_type1' => 'application/x-www-form-urlencoded',
  'host_header1' => 'api.myvideo.ge',
  'origin_header1' => 'https://tv.myvideo.ge',
  'grabber_1' => 'on',
  'gpattern_1' => '"access_token":"(.*?)"',
  'url2' => 'https://api.myvideo.ge/api/v1/programs?channelId=##channel##&shift=enabled&thumbs=enabled&startDate=##urldate2##&endDate=##stopdate2##',
  'requestOption2' => '1',
  'accept_header2' => 'application/json, text/plain, */*',
  'host_header2' => 'api.myvideo.ge',
  'origin_header2' => 'https://tv.myvideo.ge',
  'custom_header2' => 'authorization: Bearer ##grabber_1##',
  'urldate_format2' => 'Y-m-d',
  'stopdate_format2' => 'Y-m-d',
  'show' => '({"type":"Program".*?}})',
  'start' => '"startTime":"(.*?)"',
  'start_format' => 'Y-m-d H#i#s',
  'stop' => '"finishTime":"(.*?)"',
  'stop_format' => 'Y-m-d H#i#s',
  'title' => '"name":"(.*?)","',
  'desc' => '"description":"(.*?)","',
  'showicon' => '"thumbJpg":"(.*?)"',
  'channel_logo' => '||#add#https://static.myvideo.ge/media/cache/image/##cclogo##_100x100.png',
  'ccurl1' => 'https://api.myvideo.ge/api/v1/auth/token',
  'ccrequestOption1' => '2',
  'ccpost_data1' => 'client_id=7&grant_type=client_implicit',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cccontent_type1' => 'application/x-www-form-urlencoded',
  'cchost_header1' => 'api.myvideo.ge',
  'ccorigin_header1' => 'https://tv.myvideo.ge',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '"access_token":"(.*?)"',
  'ccurl2' => 'https://api.myvideo.ge/api/v1/channel?type=tv',
  'ccrequestOption2' => '1',
  'ccaccept_header2' => 'application/json, text/plain, */*',
  'cchost_header2' => 'api.myvideo.ge',
  'ccorigin_header2' => 'https://tv.myvideo.ge',
  'cccustom_header2' => 'authorization: Bearer ##grabber_1##',
  'ccchannel_block' => '{"channelId".*?,"100x100"',
  'ccchannel_id' => '"channelId":"(.*?)"',
  'ccchannel_name' => '"name":"(.*?)",',
  'ccchannel_logo' => 'cache\\/image\\/(.*?)_',
);
?>