<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'guia-tv.pt',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-04-24',
  'rev_no' => 'R0',
  'timezone' => 'Europe/Lisbon',
  'culture' => 'pt',
  'max_day' => '5',
  'episodeOption' => '1',
  'url1' => 'https://www.guia-tv.pt/mostrar-proximo-dia?c=##channel##&d=##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'content_type1' => 'text/html; charset=UTF-8',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'Y-m-d',
  'show' => '(<a.*?<\\/a>)||#exclude#class="next-day"',
  'start' => 'listing-time">(.*?)<\\/div>',
  'start_format' => 'H#i',
  'title' => 'listing-name">(.*?)<\\/div>||#replace#((?:\\:T|Ep\\.)\\d+.*?)$||',
  'season' => 'listing-name">.*?:T(\\d+)||#name#T',
  'episode' => 'listing-name">.*?Ep\\.(\\d+)',
  'channel_logo' => '||#add#https://www.guia-tv.pt/logos/##cclogo##',
  'pagekey1' => '\\srel="(.*?)"',
  'detail_url1' => '##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html, */*; q=0.01',
  'detail_content_type1' => 'text/html; charset=UTF-8',
  'detail_XMLHttpRequest1' => 'on',
  'detail_desc' => '<div class="tv-listing-desc">(.*?)<\\/div>|>|data-description="(.*?)"\\sdata-',
  'ccurl1' => 'https://www.guia-tv.pt/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'cccontent_type1' => 'text/html; charset=UTF-8',
  'ccchannel_block' => '(<div class="canal-image-name">.*?<div class="content-channel"><a.*?>)',
  'ccchannel_id' => '(?:\\?|\\&)c=(.*?)\\&',
  'ccchannel_name' => 'alt="(.*?)"',
  'ccchannel_logo' => '\\/logos\\/(.*?)"',
);
?>