<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'rtmklik.rtm.gov.my',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-08-29',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Kuala_Lumpur',
  'culture' => 'ms',
  'max_day' => '30.1',
  'url1' => 'https://rtm.glueapi.io/v3/epg/##channel##/ChannelSchedule?dateStart=##urldate1##&dateEnd=##stopdate1##&timezone=&embed=author,program',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'content_type1' => 'application/json',
  'origin_header1' => 'https://rtmklik.rtm.gov.my',
  'urldate_format1' => 'Y-m-d',
  'stopdate_format1' => 'Y-m-d',
  'show' => '({\\s*"idEPGProgramSchedule".*?})',
  'start' => '"dateTimeStart": "(.*?)"',
  'start_format' => 'Y-m-d\\TH#i#s',
  'stop' => '"dateTimeEnd": "(.*?)"',
  'stop_format' => 'Y-m-d\\TH#i#s',
  'title' => '"programTitle": "(.*?)",',
  'desc' => '"description": "(.*?)",',
  'season' => '"series": (?!0)(\\d+)',
  'episode' => '"episodeNumber": (?!0)(\\d+)',
  'channel_logo' => '"image": "(.*?)"||#addstart#https://rtm-images.glueapi.io/320x0',
  'ccurl1' => 'https://rtm.glueapi.io/v3/epg/##subpage1##/ChannelSchedule?dateStart=##urldate1##&dateEnd=##stopdate1##&timezone=&embed=author,program',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'application/json, text/plain, */*',
  'cccontent_type1' => 'application/json',
  'ccorigin_header1' => 'https://rtmklik.rtm.gov.my',
  'ccurldate_format1' => 'Y-m-d',
  'ccstopdate_format1' => 'Y-m-d',
  'ccsubpage_format1' => '#counter#1#100',
  'ccgrabber_1' => 'on',
  'ccgrabber_2' => 'on',
  'ccrequestOption2' => '1',
  'ccchannel_block' => '{\\s*"id":.*?}',
  'ccchannel_id' => '^{\\s*"id": (\\d+)',
  'ccchannel_name' => '"channel": "(.*?)"',
);
?>