<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'beinsports.com[TH]',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-05-11',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '7',
  'first_show' => '1',
  'url1' => 'https://connect-th.beinsports.com/th/tvguide/epg?channels=##channel##&unix=##urldate1##',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'host_header1' => 'connect-th.beinsports.com',
  'urldate_format1' => 'unix',
  'show' => '({\\s*"IsLiveEvent.*?})',
  'start' => '"EventStartTimeTick":\\s*(\\d+)',
  'start_format' => 'unix',
  'stop' => '"EventEndTimeTick":\\s*(\\d+)',
  'stop_format' => 'unix',
  'title' => '"Title":\\s*"(.*?)",',
  'desc' => '"SubTitle":\\s*"(.*?)",',
  'category' => '"Is(Live)Event":\\s*true,',
  'showicon' => '"CompetitionPoster":\\s*"(.*?)"',
  'channel_logo' => '"Logo":\\s*"(.*?)"',
  'ccurl1' => 'https://connect-th.beinsports.com/th/tvguide/channels',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => '*/*',
  'cchost_header1' => 'connect-th.beinsports.com',
  'ccchannel_block' => '{\\s*"ChannelId".*?}',
  'ccchannel_id' => '"ChannelId":\\s*"(\\d+)',
  'ccchannel_name' => '"Name":\\s*"(.*?)"',
);
?>