<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'nhkworldpremium.com[ja]',
  'creator_name' => 'Kivanc (せんぱい)',
  'creation_date' => '2024-02-07',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Tokyo',
  'culture' => 'ja',
  'max_day' => '7.1',
  'episodeOption' => '1',
  'url1' => 'https://nhkworldpremium.com/backend/api/v1/front/episodes?lang=ja',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/plain, */*',
  'host_header1' => 'nhkworldpremium.com',
  'urldate_format1' => '#range#Y-m-d',
  'grabber_1' => 'on',
  'gpattern_1' => '||#add###urldate1##||#replace#(,)|||',
  'show' => '({"programId".*?"schedule":"(?:##grabber_1##)\\s.*?})',
  'start' => '.*"schedule":"(.*?)"',
  'start_format' => 'Y-m-d H#i#s',
  'duration' => '.*"period":"(\\d{2}:\\d{2})||#format#t',
  'title' => '.*"programTitle":"(.*?)",',
  'subtitle' => '.*"episodeTitle":"(.*?)",',
  'language' => '.*"(english)Flg":true||#word#',
  'channel_logo' => '||#add#https://nhkworldpremium.com/img/common/logo.png?##channel##',
  'audio' => '.*"(bilingual)Flg":true',
  'pshown' => '.*"(rebroadcast)Flg":true,',
  'pagekey1' => '.*"episodeId":(\\d+)',
  'detail_url1' => 'https://nhkworldpremium.com/backend/api/v1/front/episode/##pagekey1##?lang=ja',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'application/json, text/plain, */*',
  'detail_host_header1' => 'nhkworldpremium.com',
  'detail_title' => '"program_name":"(.*?)",',
  'detail_subtitle' => '"episode_name":"(.*?)",',
  'detail_desc' => '"episode_synopsis":"(.*?)",',
  'detail_category' => '"genre":"(.*?)"||#split#(\\/)',
  'detail_showicon' => '"logo_link":"(.*?)"||#addstart#https://nhkworldpremium.com',
  'ccrequestOption1' => '1',
  'ccchannel_id' => '||#set#nhkworldpremium-ja',
  'ccchannel_name' => '||#set#NHKワールド・プレミアム',
);
?>