<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tver.jp',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-08-06',
  'rev_no' => 'R0',
  'remarks' => 'Set for Tokyo',
  'timezone' => 'Unix',
  'culture' => 'ja',
  'max_day' => '8',
  'url1' => 'https://service-api.tver.jp/api/v1/callEPGv2?date=##urldate1##&area=23&type=##ccsubpage##',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'content_type1' => 'application/json; charset=UTF-8',
  'origin_header1' => 'https://tver.jp',
  'custom_header1' => 'x-tver-platform-type: web',
  'urldate_format1' => 'Y%2Fm%2Fd',
  'show' => '{"broadcaster":{"id":"##channel##".*?"programs":\\[.*?(?:{)(.*?)(?:}}).*?\\]}',
  'start' => '"startAt":(\\d+)',
  'start_format' => 'unix',
  'stop' => '"endAt":(\\d+)',
  'stop_format' => 'unix',
  'title' => '"title":"(.*?)",',
  'category' => '"genre":"(.*?)"||#replace#(0x0)##(0x1)##(0x2)##(0x3)##(0x4)##(0x5)##(0x6)##(0x7)##(0x8)##(0x9)##(0xA)##(0xB)##(0xE)##(0xF)||ニュース／報道##スポーツ##情報／ワイドショー##ドラマ##音楽##バラエティ##映画##アニメ／特撮##ドキュメンタリー／教養##劇場／公演##趣味／教育##福祉##ex##その他',
  'pshown' => '"revival":(true),',
  'new' => '"(new)":true,',
  'lastchance' => '"last":(true)',
  'ccurl1' => 'https://service-api.tver.jp/api/v1/callEPGv2?date=##urldate1##&area=23&type=##subpage1##||#edit#(,"programs":\\[.*?}\\])##(,"genreColor":\\[.*?}\\])||##',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => '*/*',
  'cccontent_type1' => 'application/json; charset=UTF-8',
  'ccorigin_header1' => 'https://tver.jp',
  'cccustom_header1' => 'x-tver-platform-type: web',
  'ccurldate_format1' => 'Y%2Fm%2Fd',
  'ccsubpage_format1' => 'ota|bs',
  'ccchannel_block' => '"contents":\\[.*?(?:{"broadcaster":)(.*?)(?:}).*?\\]||#ccsubpage#set(ota|bs)',
  'ccchannel_id' => '#__#(.*?\\|##\\|)|#|"id":"(\\d+)',
  'ccchannel_name' => '"name":"(.*?)"',
);
?>