<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tvguide.myjcom.jp',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-06-04',
  'rev_no' => 'R0',
  'timezone' => 'Asia/Tokyo',
  'culture' => 'ja',
  'max_day' => '8',
  'url1' => 'https://tvguide.myjcom.jp/api/getEpgInfo/?channels=##channel##_##urldate1##&rectime=&rec4k=',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'Ymd',
  'show' => '({"@search\\.score".*?})',
  'start' => '"programStart":(\\d+)',
  'start_format' => 'YmdHis',
  'stop' => '"programEnd":(\\d+)',
  'stop_format' => 'YmdHis',
  'title' => '"title":"(.*?)",',
  'desc' => '"commentary":"(.*?)",',
  'showicon' => '"imgPath":"(.*?)"||#addstart#https://tvguide.myjcom.jp',
  'channel_logo' => '||#add#https://tvguide.myjcom.jp/monomedia/ch_logo/##cclogo##-400x400.png',
  'videoquality' => '"attr":\\[.*?"(sd|hd|4k)".*?\\]||#upper#',
  'audio' => '"attr":\\[.*?"(stereo|mono|dolby)".*?\\]||#word#',
  'pshown' => '"attr":\\[.*?"(rep)".*?\\]',
  'subtitles' => '"attr":\\[.*?"(cp1)".*?\\]',
  'pagekey1' => '"cid":"(.*?)"',
  'detail_url1' => 'https://tvguide.myjcom.jp/detail/?eid=##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'detail_content_type1' => 'text/html; charset=UTF-8',
  'detail_desc' => '番組内容<\\/p>\\s*<p class="mb_30">(.*?)<\\/p>',
  'detail_category' => 'href="\\/search\\/event\\/\\?genre=\\S+">(.*?)<\\/a>',
  'detail_actor' => '【出演】(.*?)(?:<\\/p>|【)||#split#(,|，)',
  'detail_director' => '【演出】(.*?)(?:<\\/p>|【)||#split#(,|，)',
  'detail_presenter' => '【司会】(.*?)(?:<\\/p>|【)||#split#(,|，)',
  'detail_commentator' => '【声】(.*?)(?:<\\/p>|【)||#split#(,|，)',
  'detail_writer' => '【脚本】(.*?)(?:<\\/p>|【)||#split#(,|，)',
  'detail_guest' => '【ゲスト】(.*?)(?:<\\/p>|【)||#split#(,|，)',
  'detail_videoaspect' => 'img src="\\/images\\/ico_(16x9)',
  'ccurl1' => 'https://tvguide.myjcom.jp/api/getChannelInfo/?targetChannels=0%2C1%2C2%2C3&areaId=108&sort=2',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'ccchannel_block' => '{"channelType".*?"channelName".*?}',
  'ccchannel_id' => '"channelType":(\\d+)|#|[|_|]"serviceId":"(\\d+)|#|[|_|]"networkId":(\\d+)',
  'ccchannel_name' => '"channelName":"(.*?)"',
  'ccchannel_logo' => 'ch_logo\\/(.*?)-400x400',
);
?>