<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'canela.tv',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-03-21',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'es',
  'max_day' => '12',
  'episodeOption' => '1',
  'url1' => 'https://www.canela.tv/?section=canalesepg',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'host_header1' => 'www.canela.tv',
  'grabber_1' => 'on',
  'gpattern_1' => '"cs_auth_token":"(.*?)"',
  'url2' => 'https://api-ott.canela.tv/getvideosegments?&banners=0&connection=wifi&device_type=tablet&for_user=0&image_format=widescreen&image_width=366&language=en&linear_channel_id=##channel##&parent_id=##channel##&parent_type=linear_channel&partner=internal&platform=web&start=##urldate2##&timestamp=##now#unix#&timezone=0000&use_device_width_widescreen=1&version=14.0||#calc#\\&start=(##urldate2##)\\&||*12',
  'requestOption2' => '1',
  'accept_header2' => '*/*',
  'host_header2' => 'api-ott.canela.tv',
  'origin_header2' => 'https://www.canela.tv',
  'custom_header2' => 'ottera-cs-auth: ##grabber_1##|#|ottera-referrer: canela.tv',
  'urldate_format2' => '#daycounter#0',
  'show' => '({"(?:type|id)":.*?"parent_type".*?})',
  'start' => '"segment_start_time":"(\\d+)',
  'start_format' => 'unix',
  'stop' => '"segment_end_time":"(\\d+)',
  'stop_format' => 'unix',
  'title' => '"name":"(.*?)",||#replace#(\\s-\\s.*?(?:\\:\\s*Episodio \\d+)?.*?)$||',
  'subtitle' => ',"name":".*?\\s-\\s(.*?)(?:\\: Episodio \\d+)?","short_description"',
  'desc' => '"long_description":"(.*?)","|>|"short_description":"(.*?)","',
  'showicon' => '"(?:original_)?thumbnail_url":"(.*?)"',
  'episode' => ': Episodio (\\d+)',
  'channel_logo' => '||#add#https://img.static-ottera.com/prod/cnm/linear_channel/logo/##cclogo##',
  'ccurl1' => 'https://www.canela.tv/?section=canalesepg',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'cchost_header1' => 'www.canela.tv',
  'ccgrabber_1' => 'on',
  'ccgpattern_1' => '"cs_auth_token":"(.*?)"',
  'ccurl2' => 'https://api-ott.canela.tv/getreferencedobjects?&banners=0&connection=wifi&device_type=desktop&for_user=0&image_format=widescreen&image_width=366&is_af_request=0&language=en&parent_id=14070&parent_type=collection&partner=internal&platform=web&timestamp=##now#unix#&timezone=0000&use_device_width_widescreen=1&version=14.0',
  'ccrequestOption2' => '1',
  'ccaccept_header2' => '*/*',
  'cchost_header2' => 'api-ott.canela.tv',
  'ccorigin_header2' => 'https://www.canela.tv',
  'cccustom_header2' => 'ottera-cs-auth: ##grabber_1##|#|ottera-referrer: canela.tv',
  'ccchannel_block' => '{"id":"\\d+","primary_id".*?"thumbnail_url":.*?}||#exclude#"name":"Home"',
  'ccchannel_id' => '"linear_channel_id":"(\\d+)',
  'ccchannel_name' => '"type":"video","name":"(.*?)"',
  'ccchannel_logo' => '"logo":".*?\\/logo\\/(.*?)"',
);
?>