<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'ionplustv.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-11-27',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '14',
  'rating_system' => 'TVPG',
  'episodeOption' => '1',
  'url1' => 'https://api.scrippscloud.com/scheduler/schedules/v2/ion_plus?start_date_parse__range=##urldate1##,##stopdate1##&offset=0&limit=100&ordering=start_ts_parse',
  'requestOption1' => '1',
  'accept_header1' => '*/*',
  'host_header1' => 'api.scrippscloud.com',
  'urldate_format1' => 'Y-m-d',
  'stopdate_format1' => 'Y-m-d',
  'show' => '({"id".*?end_ts_parse.*?})',
  'start' => '"start_ts":(\\d+)',
  'start_format' => 'unix',
  'stop' => '"end_ts":(\\d+)',
  'stop_format' => 'unix',
  'title' => '"program":"(.*?)",|>|"title_name":"(.*?)",||#replace#(\\sS\\d+.*)||',
  'subtitle' => '"title_name":"(.*?)",',
  'desc' => '"program_synopsis":"(.*?)",',
  'category' => '"title_genre":"(.*?)"|#|"program_class":"(.*?)"||#split#(,)',
  'showicon' => '"image":"(.*?)"',
  'season' => '"series_prefix":"[A-Z]+_S(?:0)?(\\d+)|>|\\sS(?:0)?(\\d+)',
  'episode' => '"title_code":"[A-Z]+(\\d+)',
  'channel_logo' => '||#add#https://ewscripps-brightspot-lower.s3.amazonaws.com/0f/4c/d1d0748a4dcda485320b0938d2a8/ionplus-logo-white1.svg',
  'production_date' => '"release_year":(\\d{4})',
  'actor' => '"cast":"(.*?)"||#split#(,)',
  'rating' => '"rating":"(.*?)"',
  'ccrequestOption1' => '1',
  'ccchannel_id' => '||#set#ion_plus',
  'ccchannel_name' => '||#set#ION Plus',
);
?>