<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'myafn.dodmedia.osd.mil',
  'creator_name' => 'Kivanc',
  'creation_date' => '2022-11-21',
  'rev_no' => 'R0',
  'timezone' => 'UTC',
  'culture' => 'en',
  'max_day' => '29',
  'rating_system' => 'TVPG',
  'episodeOption' => '1',
  'keepindexpage' => 'on',
  'url1' => 'https://v3.myafn.dodmedia.osd.mil/api/json/32/##urldate1##@0000/##urldate1##@2359/schedule.json',
  'requestOption1' => '1',
  'accept_header1' => 'application/json, text/javascript, */*; q=0.01',
  'content_type1' => 'application/json; charset=utf-8',
  'XMLHttpRequest1' => 'on',
  'urldate_format1' => 'Y-m-d',
  'show' => '({.*?})||#include#,"b":##channel##,',
  'start' => '"c":"(\\d+,\\d+,\\d+,\\d+,\\d+)||#replace#,(\\d)$||,0\\1',
  'start_format' => 'Y,m,d,G,i',
  'stop' => '"d":"(\\d+,\\d+,\\d+,\\d+,\\d+)||#replace#,(\\d)$||,0\\1',
  'stop_format' => 'Y,m,d,G,i',
  'title' => '"h":"(.*?)","',
  'subtitle' => '"i":"(?!Live)(.*?)","||#replace#(Episode \\d+)||',
  'desc' => '"l":"(.*?)","',
  'category' => '"m":"(.*?)","|#|"i":"(Live)"||#split#(,)',
  'season' => '"p":(?!0)(\\d+),"q":true',
  'episode' => '"i":"Episode (\\d+)',
  'production_date' => '"p":(\\d{4}),"q":false,',
  'rating' => '"j":"(.*?)",',
  'new' => '"k":(true),',
  'ccurl1' => 'https://v3.myafn.dodmedia.osd.mil/api/json/32/channels.json',
  'ccrequestOption1' => '1',
  'cccontent_type1' => 'application/json; charset=utf-8',
  'ccchannel_block' => '{.*?}',
  'ccchannel_id' => '"Id":(\\d+)',
  'ccchannel_name' => '"Title":"(.*?)",',
);
?>