<?php 
/*     Tempest EPG Generator (made by Kvanc)
https://github.com/K-vanc/Tempest-EPG-Generator.git  */
return array (
  'filename' => 'tvinsider.com',
  'creator_name' => 'Kivanc',
  'creation_date' => '2023-06-11',
  'rev_no' => 'R0',
  'remarks' => 'Disable Detail Page for Faster Grabbing if you do not need actor and showicon',
  'timezone' => 'America/New_York',
  'culture' => 'en',
  'max_day' => '14.1',
  'rating_system' => 'TVPG',
  'srating_system' => 'IMDb',
  'episodeOption' => '1',
  'url1' => 'https://www.tvinsider.com/network/##channel##/schedule/',
  'requestOption1' => '1',
  'accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'urldate_format1' => '#range#m-d-Y',
  'grabber_1' => 'on',
  'gpattern_1' => '||#add###urldate1##||#replace#(,)|||',
  'show' => '<h2 id="(?:##grabber_1##)".*?<div class="show-grid">.*?(?:<a class=)(.*?)(?:<\\/a>).*?<\\/script>\\s*<\\/div>',
  'start' => '<time>(.*?)<\\/time>',
  'start_format' => 'g#i A',
  'title' => '<h3>(.*?)<\\/h3>',
  'desc' => '<p>(.*?)<\\/p>',
  'category' => '<h4>([\\w\\s-]+)(?: • |<\\/h4>)',
  'season' => 'Season (\\d+)',
  'episode' => 'Episode (\\d+)',
  'production_date' => '(\\d{4})<\\/h4>',
  'pagekey1' => 'href="(.*?)"',
  'detail_url1' => '##pagekey1##',
  'detail_requestOption1' => '1',
  'detail_accept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'detail_referer_header1' => 'https://www.tvinsider.com/network/##channel##/schedule/',
  'detail_showicon' => '<img fetchpriority="high".*?src="(.*?)"',
  'detail_actor' => '(<a aria-label=".*?<\\/a>)||#exclude#<span>Director||#replace#.*?label="(.*?)".*?<\\/a>||\\1',
  'detail_role' => '(<a aria-label=".*?<\\/a>)||#exclude#<span>Director||#replace#.*?<span>(.*?)<\\/span>.*?<\\/a>||\\1',
  'detail_director' => '(<a aria-label=".*?<\\/a>)||#include#<span>Director||#replace#.*?label="(.*?)".*?<\\/a>||\\1',
  'detail_rating' => '<h4 class="show-rating">(.*?)<\\/h4>',
  'detail_star_rating' => '"IMDB Rating: (\\d+(?:\\.\\d+)?)||#addend#/10',
  'ccurl1' => 'https://www.tvinsider.com/network/tv-one/schedule/',
  'ccrequestOption1' => '1',
  'ccaccept_header1' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
  'ccchannel_block' => '<option value="\\/network\\/.*?<\\/option>',
  'ccchannel_id' => '<option value="\\/network\\/(.*?)\\/schedule',
  'ccchannel_name' => '<option value=".*?>(.*?)<\\/option>',
  'ccidremovedup' => 'on',
);
?>